### ISSUE TITLE
disabling/detaching/changing a firebase-query removes listeners from all instances

### ISSUE THREAD

**Issue by 43081j** [firebase/polymerfire#106]
Same issue as we had with firebase-document in #38.

In these places:

* https://github.com/firebase/polymerfire/blob/master/firebase-query.html#L154
* https://github.com/firebase/polymerfire/blob/master/firebase-query.html#L264
* https://github.com/firebase/polymerfire/blob/master/firebase-database-behavior.html#L73

Calling `.off()` on a ref will remove **all listeners** from **all refs to that path**, not just this particular ref.

This means, if you have two firebase-query pointing at the same place, then do one of the following:

* Detach one
* Disable one
* Change the query of one

The other firebase-query will have its listeners removed.

**Comment by miztroh** [comment]
Might this be the cause behind https://github.com/firebase/polymerfire/issues/105?

**Comment by 43081j** [comment]
@miztroh possibly. `__computeQuery(...)` is called on your example once the ref is computed. Then a second time when the orderByChild property is passed I guess. 

This would trigger a `queryChanged` which calls `.off()` and reattaches listeners to only it's self. So one of them will probably end up with no listeners. 

Not 100% though, would need to try it out to confirm its this bug.

**Comment by miztroh** [comment]
@mbleigh Can we get an update here?  This issue and / or #105 is a substantial roadblock to my project.  Thanks in advance.

**Comment by mbleigh** [comment]
We're working on it, hope to have a fix very soon.
