### ISSUE TITLE
Did something change in firebase-auth?

### ISSUE THREAD

**Issue by minakhan01** [firebase/polymerfire#117]
### Description
Cannot login with Google credentials using firebase-auth element
It worked fine for a month, but now it makes an attempt to fetch credentials, but returns invalid_client error.     

This is my code.
<firebase-app
    name="notes"
    api-key="" //my browser key in google APIs credentials
        auth-domain="beaware-140408.firebaseapp.com"
        database-url="https://beaware-140408.firebaseio.com">
    </firebase-app>

### Steps to reproduce
1. Try to login with Google here: https://beaware-140408.firebaseapp.com/
2. Inspect element to see the error: 
firebase.js:74 Uncaught Error: 
{"error":{"errors":[{"domain":"global","reason":"invalid","message":"Error getting access token from GOOGLE_OIDC, request is: https://www.googleapis.com/oauth2/v3/token?grant_type=authorization_code&cl…1D_4wo&redirect_uri=https://beaware-140408.firebaseapp.com/__/auth/handler, response is: OAuth2TokenResponse{params: error=invalid_client&error_description=Unauthorized, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDuration=null, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"}],"code":400,"message":"Error getting access token from GOOGLE_OIDC, request is: https://www.googleapis.com/oauth2/v3/token?grant_type=authorization_code&cl…1D_4wo&redirect_uri=https://beaware-140408.firebaseapp.com/__/auth/handler, response is: OAuth2TokenResponse{params: error=invalid_client&error_description=Unauthorized, httpMetadata: HttpMetadata{status=401, cachePolicy=NO_CACHE, cacheDuration=null, staleWhileRevalidate=null, filename=null, lastModified=null, headers=HTTP/1.1 200 OK\r\n\r\n, cookieList=[]}}"}}

This may not be specifically the polymfire element issue, but maybe a firebase or google api one. Please let me know if you happen to know what's causing it. Thanks!

**Comment by abehaskins** [comment]
Are you still experiencing this issue? If so please re-open this bug.

**Comment by Cmillar176** [comment]
Was there a solution to this? Experiencing the same thing

**Comment by tomermes** [comment]
+1

**Comment by dariuszblaszkiewicz** [comment]
Same thing... It appears sometimes on android devices.

**Comment by alexpriceco** [comment]
Also having this, twice this evening. What's up with this error?

**Comment by lennonjesus** [comment]
Same problem here.

The error is fired, but the user is authenticated.

**Comment by tacticalpoptarts** [comment]
Same issue here.  User is logged in but initial auth callback returns an error saying that the token has already been redeemed.  The resultant user payload is null but the proper tokens are set in local storage and the user gets created in Firebase.

If I put another firebase `.onAuthStateChanged()` listener in the Google sign-in error callback, the auth state change fires a second time and the user is logged in (read: the Firebase SDK now recognizes the user) correctly.

**Comment by jashanbhullar** [comment]
Was anybody able to solve this error?

**Comment by tjmonsi** [comment]
Going to replicate it from here
