### ISSUE TITLE
Using <firebase-query> with polymerfire

### ISSUE THREAD

**Issue by esd100** [firebase/polymerfire#118]
Before anyone makes a comment about me not trying to figure things out on my own.

I have read through those firebase docs (https://firebase.google.com/docs/reference/js/firebase.database.Query) about 3 times today. I also read through the source code ( e.g. https://github.com/firebase/polymerfire/blob/master/firebase-query.html) about 3 times today.

I essentially have data setup like this:

```
{
Logs: {
$uid: {
$logID:{
logMetaData}}},

Users: {
$uid:{
userMetaData}},

Groups: {
admin: {
members: {
$uid}},
users: {
members: {
$uid}}}
}
```

I’m trying to use `firebase-query` like this:
```
    <firebase-query
      id="adminLogQuery"
      app-name="Nuclear Medicine Log"
      path="/Logs"
      order-by-child="Authorized User"
      equal-to="[[user.displayName]]"
      data="{{data}}"
      log>
    </firebase-query>
```
Essentially, within the logMetaData, there is a key called “Authorized User” and I want to match the “user.displayName” to the values for the “Authorized User”.

I would like to define `path="Logs/[[uid]/[[logId]]"` but I’m not sure how I would have `uid` or `logID` defined (or pre-defined) as properties, since there are so many entries that vary. The `$uid` is a variable scramble of letters and numbers, while the `$logID` are variable timestamps

I’m not sure if `orderByChild` traverses multiple levels that are deep to the root.

I’m also not sure whether it is better to use the `query` object attribute or the “query” `method` attributes, as defined in the source code.

i.e., 
`query="{ "orderByChild":"Authorized User", "equalTo":"John Doe"}"`
also, what is `ref`?

vs.

`orderByChild="Authorized User"` `equalTo="{"Authorized User":"John Doe"}"`

**Comment by esd100** [comment]
Is anyone able to help?

**Comment by tjmonsi** [comment]
@esd100 
The orderByChild should be an attribute of the path /Logs
Seeing that your Logs has a structure of:

```
Logs: {
  $uid: {
     $logID:{
         logMetaData
      }
   }
}
```

Then it doesn't have an attribute of Authorized User...

If you want to look at the logs of a specific uid using the user, instead of user.displayName, it would be best to use user.uid if the $uid in the Logs are the actual user.uid values of the users registered.

You can then use this

```
<firebase-query
      id="adminLogQuery"
      app-name="Nuclear Medicine Log"
      path="/Logs/[[user.uid]]"
      data="{{data}}"
      >
</firebase-query>
```

To answer your additional questions:
1.`orderByChild` only orders the results based on the values of the attribute of the items under the path
2. You would use `query` to get an array of results that you want to order and filter, especially if the objects under the path are "array-like" and not "object-like"
3. ref is path :smile:

Hope this helps

**Comment by esd100** [comment]
@tjmonsi thanks for your input.

Unfortunately, I think the only way that I can accomplish what I want is by making multiple references to the actual information in multiple places, so that I can end up getting the actual information I want.

A log is placed by a user but has an authorized user, who has to verify the log. Once a log is submitted, the authorized user is notified and then logs in. The authorized user will look at the data in the log and verify it.

So, as for using `query` vs the `query "methods"` in the `firebase-query`, I'm still not sure why I would want to use one vs the other.

**Comment by tjmonsi** [comment]
What do you mean query methods?

So the specs need that the query be `query="{ "orderByChild":"Authorized User", "equalTo":"John Doe"}"`
What would the firebase structure be like (with data) and given a query that you want, what would be the returned data?

**Comment by esd100** [comment]
@tjmonsi 

So, I know it's kind of weird terminology, but what I mean is that the `firebase-query` element allows you to put in `attributes` that are what I think of as `query "methods"`

i.e.,
```
    <firebase-query
      id="adminLogQuery"
      app-name="Nuclear Medicine Log"
      path="/Logs"
      order-by-child="Authorized User"
      equal-to="[[user.displayName]]"
      data="{{data}}"
      log>
    </firebase-query>
```
where, in my mind, `order-by-child` is an attribute and `query "method"`.

But, looking at the source code, it seems that I could equivalently write, for example:
```
    <firebase-query
      id="adminLogQuery"
      app-name="Nuclear Medicine Log"
      path="/Logs"
      query="{ "orderByChild":"Authorized User", "equalTo":"[[user.displayName]]"}"
      data="{{data}}"
      log>
    </firebase-query>
```


The source code has the following `properties`:

```
properties: {
          /**
           * [`firebase.database.Query`](https://firebase.google.com/docs/reference/js/firebase.database.Query#property)
           * object computed by the following parameters.
           */
          query: {
            type: Object,
            computed: '__computeQuery(ref, orderByChild, limitToFirst, limitToLast, startAt, endAt, equalTo)',
            observer: '__queryChanged'
          },

          /**
           * The child key of each query result to order the query by.
           *
           * Changing this value generates a new `query` ordered by the
           * specified child key.
           */
          orderByChild: {
            type: String,
            value: ''
          },

          /**
           * The value to start at in the query.
           *
           * Changing this value generates a new `query` with the specified
           * starting point. The generated `query` includes children which match
           * the specified starting point.
           */
          startAt: {
            type: String,
            value: ''
          },
...
```

**Comment by esd100** [comment]
I know that it is weird terminology. I think I figured it out though.

Initially, I thought from reading the source code, that the `query` property could be set as an attribute. But reading over it again, I realize that it is computed from the other properties, which are put in as `attributes`.

**Comment by tjmonsi** [comment]
Ahh you can't do the query like that because it uses computed. That means
it is a readonly attribute and the value is being computed based on the
values put in the attributes order-by-child, path (which is where ref is
computed), limit-to-first, limit-to-last, start-at, end-at, and equal-to

**Comment by esd100** [comment]
@tjmonsi yeah, that is what I finally realized. Thanks for the input!

I'm still having a lot of trouble structuring and working with my data though.

**Comment by tjmonsi** [comment]
I did some documentation on my part on structuring data so you can filter
lists: “Learning Firebase: Structuring your data to show filtered list —
Making a blog pt. 1”

https://medium.com/@tjmonsi/learning-firebase-structuring-your-data-to-show-filtered-list-making-a-blog-pt-1-b4f4635c05a4

If you have questions just ask away :)

**Comment by mbleigh** [comment]
This seems like more of a general Firebase issue than a PolymerFire one. Suggested reading: [Structure Your Database](https://firebase.google.com/docs/database/web/structure-data).
