### ISSUE TITLE
QUESTION: Can Firebase be a "Headless CMS" ?

### ISSUE THREAD

**Issue by oneezy** [firebase/polymerfire#119]
# Firebase "Headless CMS" ?
-----
I'm just hearing of this new term "Headless CMS". 

Being that Firebase is a real-time db + a lot more things out of the box, I'm trying to make the connection here (being a UI/UX guy).

Has anything by the Firebase team written up anything on this or can point me to the right direction?

**Comment by tjmonsi** [comment]
What do you mean Headless CMS?

**Comment by oneezy** [comment]
Have a look at this article: 
https://css-tricks.com/what-is-a-headless-cms/

And a listen to this Podcast: 
http://shoptalkshow.com/episodes/204-matt-dennewitz-jeff-eaton/

**Comment by mbleigh** [comment]
Yes, but that's not really a question about PolymerFire. Please use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk) Google Group or StackOverflow (with a more specific question).

**Comment by zthomas** [comment]
There are some projects that turn Firebase into a headless CMS. I recently built [PushTable](www.pushtable.com) which adds an AirTable like (data table, cms input types etc) interface on top of your Firebase Firestore database.
