### ISSUE TITLE
firebase-document stop sync to memory

### ISSUE THREAD

**Issue by rof20004** [firebase/polymerfire#120]
### Description
firebase-document does sync to memory always

### Expected outcome

I want to save a document when i click a button and not sync to memory, because i stay in same form, and with sync to memory my inputs always update latest object in my database. I do not want this.

### Steps to reproduce
1. Create a form with two paper-input
2. save this inputs like {{contact.name}} and {{contact.telephone}}
3. After save change the inputs with anothers values and see that sync to memory update my database, I do not want this.

### Browsers Affected
- [ ] Firefox

**Comment by tjmonsi** [comment]
I suggest not to connect the data to firebase-document's data value. The current behavior is that it automatically syncs in with the data with whatever you put in the forms. There are observers that check changes in the immediate attribute of the object, based on the inherited functions from app-storage-behavior. You can check the flow by looking at: https://github.com/PolymerElements/app-storage/blob/master/app-storage-behavior.html lines 69-71, then 408-429, then 306-308, then at https://github.com/firebase/polymerfire/blob/master/firebase-document.html lines 173 (which replaces the setStoredValue at app-storage-behavior.

Just like i have suggested, we could do this:

```
<firebase-document
  path="/[[somePath]]"
  data="{{fData}}">
</firebase-document>
```

```
  // at scripts part
  observers: [
     '_dataChanged(fData.*)'
  ],

  _dataChanged() {
    this.set('contact', this.fData);
  }
```

Then what you can also do is this:

```
  onSave: function() {
    this.set('fdata', contact);
  }
```

Or Maybe we could ask to add a disable-auto-saving flag? But that would depend on the thrust of the polymerfire team

**Comment by rof20004** [comment]
Thanks @tjmonsi  for the answer, I will read it with care. About auto-saving flag, I think this is the best to do.

**Comment by rof20004** [comment]
Hi @tjmonsi , reading your answer and firebase source code, I found that attribute disabled="true" does what I want, I do not know if this attribute was created to stop sync, but it stops all listener and works like I want.

https://elements.polymer-project.org/elements/polymerfire?active=firebase-document

disabled: When true, Firebase listeners won't be activated. This can be useful in situations where elements are loaded into the DOM before they're ready to be activated (e.g. navigation, initialization scenarios).

Now it is working like I wished.

**Comment by tjmonsi** [comment]
Actually I was reading that, but looking at the code, the disabled=true only stops from synchronizing your data from firebase to firebase-document. But again, if anything changes from contact.name, it will still save it to firebase. Is that what your specs needed?

**Comment by tjmonsi** [comment]
Oh right, now I went back and read your original post. Yep disabled is the one you need :smile:

**Comment by rof20004** [comment]
Yeah :dancer: 
hehehehe

**Comment by rof20004** [comment]
I need to close this issue @tjmonsi  ?

**Comment by tjmonsi** [comment]
I think. Your call hehehe :)

**Comment by rof20004** [comment]
Thanks for help @tjmonsi , disabled="true" solves my problem.
