### ISSUE TITLE
Refreshing or Re-logging in will delete bound data

### ISSUE THREAD

**Issue by esd100** [firebase/polymerfire#123]
So, I tried searching the internet for an answer, but the only thing I came up with which was anything similar was this (https://github.com/firebase/angularfire/issues/14).

I have a similar problem.

Whenever I `refresh` or `close & re-login`, a very specific subset of data in the database gets deleted.  I've searched my entire project for any references that might be stray, but got nothing. I even locked-down my `firebase-document` as a child within `template dom-if` set to false, but it still occurs.

I can close the window and be looking at the database in firebase console and see the data. But, as soon as I reopen the window and re-login or refresh the page, the specific set of data gets deleted.

I don't know what's happening. I don't know how to make a reduced test case.

If there is a way to debug this by sharing the project, I can do that.

**Comment by esd100** [comment]
Can anyone help me with this? I'm still having the same issue.

I essentially have data setup like this:
```
{
    Logs: {
        $uid: {
            $logID:{
                logMetaData
            }
        }
    },

    Users: {
        $uid:{
            userMetaData: {
                Logs: {
                    $logID
                }
            } 
        }
    },

    Groups: {
         admin: {
            members: {
                $uid
            }
        },
        users: {
            members: {
                $uid
            }
        }
    }
}
```

I'm using `firebase-document` to submit the full log into the `Logs: {$uid: {$logID:{logMetaData` and also to put a reference to the logID in the `Users: {$uid:{userMetaData:{Logs:{$logID`

Whenever I refresh the page, the `Logs:{$logID` gets deleted from the `Users: {$uid:{userMetaData:{Logs:{$logID` for the user that is logged in.  However, the `$logID:{logMetaData` in the `Logs: {$uid: {$logID:{logMetaData` does not get deleted.

Could some please explain what is going on?

I have a feeling it has something to do with whatever `firebase-document` does when it initializes and synchronizes. For example, when the page is refreshed, the `data-bound` properties have no value, and for some reason `firebase-document` is saying, `ok, delete whatever is in the database`.

**Comment by katowulf** [comment]
Most likely, the data is not actually written to the database. It's certainly not deleted from the database while your app is offline, unless you've set up onDisconnect handlers or a server-side process.

Minimal repro, version info, errors in JS console, code showing that you're capturing cancel callbacks and errors in reads/writes, and steps to see and reproduce the problem will likely be necessary to get very far here.

**Comment by katowulf** [comment]
Also, setting up debug logging may help:

JS:  firebase.database().enableLogging(true);
iOS:  [FIRDatabase setLoggingEnabled:YES];
Android:  FirebaseDatabase.getInstance().setLogLevel(Logger.Level.DEBUG);

**Comment by esd100** [comment]
@katowulf If I can see the data in the `https://console.firebase.google.com/` in a separate window, doesn't that mean that the data is written to the database?

**Comment by esd100** [comment]
Also, I'm using `polymerfire`, so I don't know how to do the logging stuff that you mentioned.  The only option that I know of is writing
```
    <firebase-document
      id="addLogtoLogs"
      app-name="NML"
      path="/Logs/[[user.uid]]/[[logid]]"
      data="[[newLog]]"
      log>
    </firebase-document>
```

**Comment by esd100** [comment]
@katowulf did you get my messages?

**Comment by e111077** [comment]
Hi @esd100. All polymerfire elements create a global firebase variable. To enable logging, in your polymer javascript that has a `firebase-app` element already created and attached, you can simply run

`firebase.database.enableLogging(true)`

**Comment by mbleigh** [comment]
```html
    <firebase-document
      id="addLogtoLogs"
      app-name="NML"
      path="/Logs/[[user.uid]]/[[logid]]"
      data="[[newLog]]"
      log>
    </firebase-document>
```

This is problematic right here -- you have `data="[[newLog]]"` which is a one-way (down) binding. That means that this will only ever write, and never read. Try `data="{{newLog}}"` and see if you get a different result. Otherwise I'll need to see more of your code to know how to help.

**Comment by esd100** [comment]
Thanks @e111077 @mbleigh. Now that I figured out how to enable logging, I think I know what the problem is.

I think that the data is being overwritten, and in the process the data is being deleted.

In my login element, I have user metadata written to the Users:{$uid:{metadata.  In my form element, I have log reference info written to Users:{$uid:{Logs:{$logid. So, when I refresh the page, the login element essentially overwrites the entire Users:{$uid:{... data tree, disregarding the presence of the Logs:{$logid information, resulting in the deletion.

I'm not sure how to fix it, but I think I will implement some query logic in my login element to see if user metadata already exists, and then writing or not writing depending on whether info is present.

Does that sound like a good hypothesis? I'm  I  You

**Comment by esd100** [comment]
Argh...polymerfire is driving me crazy.

In trying to implement some logic, as described above, now, I'm getting the error:
`Cannot create property '$key' on string`

**Comment by esd100** [comment]
After using the branch mb-leaf-query (https://github.com/firebase/polymerfire/pull/96), that fixed the issue above `Cannot create property '$key' on string`.

Then, I was able to implement some logic in my `login-element` to check and see if there was data already present and, if present, to use `template is="dom-if"` with the bound conditional property set to false, so the `firebase-document` elements nested within don't get fired.

This solved my problem.

Thanks for your help folks!
