### ISSUE TITLE
firebase-query how load the list when open page for first time

### ISSUE THREAD

**Issue by rof20004** [firebase/polymerfire#124]
### Description
firebase-query not loading my list when open the page for first time.

I created ready function but i do not know how load the list of my database.

### Expected outcome
execute firebase-query to get my list from database

### Actual outcome
Does nothing

### Steps to reproduce

1. Call firebase-query element on page

<firebase-query
      id="query"
      path="https://polymer-test-6f997.firebaseio.com/user/[[user.uid]]/contatos"
      data="{{contatoList}}"
      log>
    </firebase-query>

2. Open the page in a web browser.

### Browsers Affected
- [ X] Chrome
- [ X] Firefox

**Comment by tjmonsi** [comment]
Path should not be that but the relative path of data.

so it should be
```
<firebase-query
id = "query
path = "user/[[user.uid]]/contatos"
data = "{{contatoList}}">
</firebase-query>
```

provided that you already have instantiated `<firebase-app>` before

**Comment by rof20004** [comment]
Many thanks @tjmonsi , your answer is correct, I did not know about this firebase-query particularity.
