### ISSUE TITLE
QUESTION: Relational Data

### ISSUE THREAD

**Issue by JGSolutions** [firebase/polymerfire#127]
How can I use straight firebase-query to get relational data. Currently using the the straight up firebase SDK what for example:

`
 var itemsRef = this.firebase.database().ref('/items');
 var catRef = this.firebase.database().ref('/categories');
  itemsRef.on('child_added', function(snap) {
     catRef.child(snap.val().category).once('value').then(function(snapshot) { }.bind(this));
 }.bind(this));
`

**Comment by abehaskins** [comment]
This is a question better asked on StackOverflow :)
