### ISSUE TITLE
Authentication with Firebase-auth to use google APIs

### ISSUE THREAD

**Issue by esd100** [firebase/polymerfire#128]
As far as I know, there is authentication with `firebase-auth` and authentication with `google-signin`, but it doesn't seem that `google-signin-aware` is aware of authentication with `firebase-auth`.

How can I use the existing `polymerfire` elements to facilitate the use of google-api?

**Comment by dwberry** [comment]
I had this issue, and https://github.com/firebase/polymerfire/issues/103
Solved it.

What you want is to forget firebase for a minute and setup <google-signin> and <google-signin-aware> like normal. According to the docs...
Then get a credential from Google signin and then.... you can use that credential with <firebase-auth>.

Firebase doesn't give you the correct token type to access Google APIs directly. I'm a newbie at auth, so it took about a month for me figure that out.. now it's easy.
