### ISSUE TITLE
Error/Warning when retrieving an Array using firebase-query

### ISSUE THREAD

**Issue by milesje** [firebase/polymerfire#135]
### Description
When using firebase-query to retrieve an array from the DB an Error/Warning is show in the console. 
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot create property '$key' on string 'Test 1'
  
```
<firebase-query
    id="query"
    log
    path="/questions"
    data="{{data}}"
    >
</firebase-query>
```
### Expected outcome
An array should be returned.

### Actual outcome
An Error is thrown

### Sample DB
```
{
  questions: {
     0: "Test 1",
     1: "Test 2",
     2: "Test 3"
  }
}
```

![my_app](https://cloud.githubusercontent.com/assets/537359/19664430/e7f73860-9a05-11e6-99c3-cc330ea7d03c.png)

**Comment by mbleigh** [comment]
`firebase-query` is not intended to be used on coerce-able arrays inside a Firebase Database. In general, we discourage using numeric indices at all. You *may* be able to use `firebase-document` at the same path to get an array, but that may also have edge cases.

This is also tangentially related to #96
