### ISSUE TITLE
How to get the JWT?

### ISSUE THREAD

**Issue by skhaz** [firebase/polymerfire#137]
How can I get the idToken (JWT) of current user logged?

1 - (Verifying ID Tokens)[https://firebase.google.com/docs/auth/server/verify-id-tokens]

**Comment by mbleigh** [comment]
Have you tried:

```html
<firebase-auth user="{{user}}"></firebase-auth>
<script>
/* ... */
this.user.getToken().then(token => { console.log(token); });
/* ... */
</script>
```

See https://firebase.google.com/docs/reference/js/firebase.User#getToken
