### ISSUE TITLE
Add sendPasswordResetEmail

### ISSUE THREAD

**Issue by chuckh** [firebase/polymerfire#147]
### Description
Add missing sendPasswordResetEmail

### Expected outcome

Can send reset password email.

### Actual outcome

Can't send reset password email.  Get error message.

### Live Demo
n/a

### Steps to reproduce
this.$.auth.sendPasswordResetEmail('test1@test.com')

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by siddv** [comment]
Hey, I notice this fix is on master, but hasn't been pushed to a tag yet. Would it be possible to push a new version out with this fix please?
