### ISSUE TITLE
Feature detection for firebase-messaging

### ISSUE THREAD

**Issue by Scarygami** [firebase/polymerfire#150]
With the Push API and Service workers not available across all browser vendors yet, it would be nice to have a property included in the `firebase-messaging` element that tells you whether you can actually use the element.

That property could be used to e.g hide UI-elements that would allow users to activate push notifications, e.g. for subscribing to topics.

It's easy enough to do this check with `('serviceWorker' in navigator && 'PushManager' in window)` but having this check included in the element directly would make sense in my opinion.

If you agree I can create a PR, just not sure what name would be appropriate for the property, or if this functionality should actually be included in the underlying firebase sdk first.

**Comment by mbleigh** [comment]
I'd accept this as a PR, let's call the boolean prop `push-supported`.
