### ISSUE TITLE
Add element for remote config

### ISSUE THREAD

**Issue by phidias51** [firebase/polymerfire#152]
It would be useful to be able to access remote config data from an element.  Something like this:

```html
<firebase-remote-config key="myConfigParam" value="{{myConfig}}"></firebase-remote-config>

```

**Comment by mbleigh** [comment]
Remote Config is not currently a part of the Firebase JS SDK (though I'd love to see it become so!). Until it is, we can't really do anything to support it in PolymerFire.

Closing, though feel free to reopen or repost if Remote Config comes to JS-land :)

**Comment by phidias51** [comment]
If firebasejs is the driver for these issues, can you link them to the equivalent issue in the firebasejs project?  It would perhaps give them some idea of where the requests are coming from.

**Comment by mbleigh** [comment]
We don't have a public bug tracker for the Firebase SDK, but I'd encourage you to make your opinion known here: https://firebase.google.com/support/contact/bugs-features/
