### ISSUE TITLE
Ad Mob Element Support

### ISSUE THREAD

**Issue by phidias51** [firebase/polymerfire#153]
I know Google differentiates between Ad Words and Ad Mob (but developers don't really care).  If you're developing a web mobile application, you expect to be able to use whatever ad platform Firebase supports. We just need a way to be able to serve ads. Something like this

```html
<firebase-ad keywords="[[keywords]]"></firebase-ad>
```

There should be some way for the ad to be styleable (at last in terms of height and width), and perhaps make that so that you can make the ad responsive to device dimensions, and available slot space.

The ad should be servable in a non-blocking way (serve them up in the background thread), and should automatically allocate visual space for it.  Nobody likes screens that keep shifting around while they're loading content.

**Comment by mbleigh** [comment]
PolymerFire is a wrapper for the Firebase JS SDK, of which AdMob is not a part. If it ever becomes such, we'd be happy to add support here.
