### ISSUE TITLE
Create new document

### ISSUE THREAD

**Issue by bnason** [firebase/polymerfire#154]
What is the correct way of adding a completely new document to the firebase db?

**Comment by mbleigh** [comment]
You can just set data on a `firebase-document` path:

```html
<firebase-document path="/my/new/doc" data="{{data}}"></firebase-document>
<script>
/* ... */
  this.data = {brand: 'new', data: true};
/* ... */
</script>
```

**Comment by bnason** [comment]
Yea, I was trying to avoid dynamically creating new elements via javascript.

Is there any way to access the javascript api in the firebase-app element so I could do the following?
`var newTransactionKey = firebase.database().ref().child('transactions').push(transaction).key;`
Assuming it's using the API from here: https://firebase.google.com/docs/database/web/read-and-write

**Comment by mbleigh** [comment]
You can just do exactly what you wrote :)

**Comment by bnason** [comment]
When I use that exact line, I get the following error:

`firebase-app.js:26 Uncaught TypeError: c[b] is not a function(…)`

**Comment by mbleigh** [comment]
If you're loading polymerfire modularly, you need to make sure you're
including firebase-document or firebase-query (or
firebase-database-script). It may be that your <firebase-app> registered
before the firebase-database script loaded, which would mean that the app
didn't initialize with database ready.

Also double-check that you're not using the "name" attribute on
<firebase-app>

**Comment by bnason** [comment]
Thanks! That fixed it.
