### ISSUE TITLE
firebase-auth works in firefox but not in mobile chrome or desktop chromium

### ISSUE THREAD

**Issue by n1ywb** [firebase/polymerfire#156]
### Description

Given a fresh polymer starter kit app and adding polymerfire firebase-auth, authentication works as expected in Firefox but does not work in Chrome on desktop or mobile.

### Expected outcome

Successful authentication

### Actual outcome

In not-developer mode, the authentication popup appears, is blank, and disappears after a few seconds.

In developer mode, the authentication popup contains another instance of the app. Errors are also present on the JS console; see screenshot.

Firefox: 

![screenshot from 2016-11-21 13-46-50](https://cloud.githubusercontent.com/assets/316961/20483507/99048070-aff2-11e6-8625-006d81632dec.png)

Chromium: 

![screenshot from 2016-11-21 13-47-38](https://cloud.githubusercontent.com/assets/316961/20483524/a9616b4a-aff2-11e6-89e4-1a1989b4b890.png)

Chromium in dev mode:

![screenshot from 2016-11-21 13-52-20](https://cloud.githubusercontent.com/assets/316961/20483676/9a1ba910-aff3-11e6-911a-dc7b29ac91a9.png)

Chrome on my android phone does the same thing as chromium dev mode on my laptop; instead of the auth window popup I get a popup with the app in it

### Live Demo

Live app: https://fir-auth-f986a.firebaseapp.com/

Source code: https://github.com/n1ywb/polymerfire-auth-test

### Steps to reproduce

1. create new polymer starter kit app
1. add firebase auth feature
1. serve locally or deploy to firebase, same either way
1. Open live app link in chrome not in dev mode
1. click log in in app drawer
1. Open live app link in chrome in dev mode
1. click log in in app drawer

### Browsers Affected

- [x] Chrome mobile
- [X] Chromium Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 18 (64-bit)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### Versions

    polymerfire#0.10.3
    firebase#3.6.1
    polymer#1.7.0

**Comment by mbleigh** [comment]
You need to exclude the  /__/ URL namespace from your navigation fallback
in your service worker. It looks like is overriding the auth widgets hosted
in the reserved namespace.

**Comment by n1ywb** [comment]
Ah, I bet that's what this line does https://github.com/notwaldorf/mojibrag/blob/master/sw-precache-config.js#L18

    navigateFallbackWhitelist: [/^(?!\/__)/, ' /getProjectConfig/'],

**Comment by n1ywb** [comment]
hm, adding that line didn't help. In fact, the service worker is disabled when serving locally with `polymer serve`, so I'm not sure how it could cause this issue

**Comment by n1ywb** [comment]
I stand corrected; it IS working better after I add that line AND deploy to firebase (durrr). Thanks for the help. I might suggest adding this to the docs.

**Comment by n1ywb** [comment]
related issue with mention of the magical whitelist config https://github.com/Polymer/polymer-build/issues/35
