### ISSUE TITLE
Firebase-document throws warning after succesful signin with redirect

### ISSUE THREAD

**Issue by TimvdLippe** [firebase/polymerfire#16]
### Description
I get a warning in my console regarding `synchronous XMLHttpRequest` when using `<firebase-document>`. I sign in with redirect and after I get returned back to my website, the warning is thrown. `<firebase-document>` remains functional and retrieves/saves data as usual, but when the user is redirected back to the website this warning is thrown.

### Expected outcome
No warning displayed

### Actual outcome
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

### Live Demo
I am not sure how to create a demo for this, it is happening in our full-blown application.

### Steps to reproduce
1. Use Sign in with Redirect on `firebase-auth`
* Open the page in a web browser.
* Wait for the redirect
* Accept the provider
* Get redirected back to the website
* Let `<firebase-document>` trigger and receive data
* Observe the warning is thrown in the console

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cdata** [comment]
@TimvdLippe thanks for reporting. There is a good chance that this is a Firebase SDK issue.
@mbleigh any thoughts on how best to triage this?

**Comment by mbleigh** [comment]
This is just a piece of the underlying mechanics of the Firebase Database SDK. It's nothing to worry about and is safe to ignore (also not something PolymerFire specifically can do anything about).
