### ISSUE TITLE
polymerfire no longer working after v0.10.1

### ISSUE THREAD

**Issue by andrewspy** [firebase/polymerfire#161]
### Description
polymerfire no longer working after `v0.10.1`, specifically `<firebase-document>` and `<firebase-query>`. Was developing with `v0.9.7` all the while with no issue, and notice no longer working after updating the latest version (i.e. `v0.10.3`). I have traced the last know working version to be `v0.10.0`. Not sure if other have similar issue, or there is any breaking changes between `0.10.1` and `v0.10.0`.

### Expected outcome

data is return (via data-binding)

### Actual outcome

No data is returned (via data-binding)

### Live Demo
N/A

### Steps to reproduce

It's a bit hard to reproduce as in involve the whole application. Will try to isolate and reproduce if others is having similar issue.

### Browsers Affected

- [x] Chrome

**Comment by mbleigh** [comment]
Something to try: add a `<link rel="import" href="bower_components/polymerfire/polymerfire.html">` at the very top of your app. My best guess is that you're initializing `firebase-app` before your document and query elements are upgraded.

**Comment by andrewspy** [comment]
@mbleigh You were right on the spot (except that it should be `firebase.html` instead of `polymerfire.html`. Prior to `v0.10.1` I was able to run polymerfire by only importing individual element (i.e. `<firebase-app>`, `<firebase-auth>` etc...) without importing `<link rel="import" href="bower_components/polymerfire/firebase.html">` at the top. Importing that did resolve the issue.

I also suggest adding documentation that importing `firebase.html` as a prerequisite, as it is not mentioned anywhere in the documentation.

Thanks!
