### ISSUE TITLE
are you going to support providers scopes in firebase-auth?

### ISSUE THREAD

**Issue by khammami** [firebase/polymerfire#163]
Hi,

by using firebase SDK for web we can add more params to the authentication like scopes for providers. unfortunately this feature is not implemented yet in polymerfire.

is there anyway/workaround to add scopes with the actual firebase-auth?

**Comment by mbleigh** [comment]
```html
<firebase-auth id="auth" user="{{user}}"></firebase-auth>
<script>
  let auth = document.getElementById('auth');
  let google = new firebase.auth.GoogleAuthProvider();
  google.addScope('http://scope/here');
  auth.signInWithPopup(google);
</script>
```
