### ISSUE TITLE
Is there a equivalent `orderByKey` properties for `<firebase-query>`?

### ISSUE THREAD

**Issue by andrewspy** [firebase/polymerfire#165]
Is there a equivalent `orderByKey` properties for `<firebase-query>`?

**Comment by Shah-Parth** [comment]
@andrewspy take a look at https://youtu.be/3WTQZV5-roY?t=1m10s

**Comment by andrewspy** [comment]
@Shah-Parth I have seen that, `<firebase-query>` does provides Properties for `orderByChild`and `orderByValue`, but missing `orderByKey` Properties.

**Comment by ooscarr** [comment]
I've seen that `limitToFirst` tag attribute is in realitya dashed `limit-to-first`

**Comment by raydaly** [comment]
It appears that **by default firebase-query uses orderByKey** when orderByChild or orderByValue are not used. I ran a simple test using orderByChild and then removed it. When I removed it the result was sorted by key.  Also in the code where the query is built there is this:

`if (orderByChild) {
            query = ref.orderByChild(orderByChild);
          } else if (orderByValue) {
            query = ref.orderByValue();
          } else {
            query = ref.orderByKey();
          }`

My firebase-query to test this looked like this before removing the orderByChild
`    <firebase-query id="query"
      path="/tweets"
      data="{{tweets}}"
      order-by-child="created_at"
      >`

**Comment by vinceyoumans** [comment]
How would you do an orderByChild, but in reverse?

**Comment by andrewspy** [comment]
@raydaly Thanks for the info, and I shall close the issue.
