### ISSUE TITLE
Document that path on firebase-document is case-sensitive

### ISSUE THREAD

**Issue by TimvdLippe** [firebase/polymerfire#17]
### Description
This took me quite a while to figure out why my `firebase-document` was not working properly. It turned out that the `path` of the element contained capital characters. E.g. `/path/Polymer` instead of `/path/polymer`.

### Expected outcome
When the `path` of a `firebase-document` contains uppercase characters, requests to Firebase will be successful.

### Actual outcome
As a result of the path containing uppercase-characters, the request of `firebase-document` is unsuccessful. After that, most of the properties on `firebase-document` would reset. It did sometimes throw Errors, other times it just removed references to the `app` and `ref`. `data` was set to `{}`.

### Sample code
```html
<firebase-app
        name="test">
</firebase-app>
<firebase-document
        app-name="test"
        path="/users/TimvdLippe"
        data="{{user}}"
></firebase-document>
```

### Steps to reproduce
1. Use the above `firebase-app` and `firebase-document`
* In Firebase on the end-point `/users/TimvdLippe` store `"User retrieved!"`
* Open the above example in the browser
* Output the content of `data` of the `firebase-document`. This should be `{}`.
* Modify the above example by setting `path="/users/timvdlippe"`
* Refresh the browser
* Output the content of `data` of the `firebase-document`. This should be `"User retrieved!"`

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cdata** [comment]
Thanks for reporting. I must admit that after reading the description, I'm still not sure what problem you are trying to report.There doesn't seem to be a connection between the expected outcome and the actual outcome. Your expected outcome involves the path, but the actual outcome pertains to the data. Furthermore, your steps to reproduce say to set the data-binding, but don't specify which property to set (the `path`?).

Are you requesting that the path always be made lowercase? Or are you saying that the casing of the path should always be preserved but isn't? Please try to be more clear when describing the problem!

Also, if you could provide a repro case (as prescribed by the contributor guidelines) in plain text, I can hook it up to my own Firebase project and try it out.

**Comment by TimvdLippe** [comment]
@cdata Sorry for causing so much confusion. This problem was confusing for me and as a result this issue report was not as clear as it should have been. I have updated the post above which includes the plain text repro case and updated the steps on how to see it in action.

**Comment by TimvdLippe** [comment]
Gist from our Slack conversation: It appeared that my initial test case was constructed incorrectly. The data in my Firebase was lowercase instead of the String with the uppercase characters. We agreed that adding a note to notify new developers of the case sensitivity of the `path` property would clear up initial confusion.
