### ISSUE TITLE
firebase-query not working inside component

### ISSUE THREAD

**Issue by iadj** [firebase/polymerfire#172]
### Description

- Using Polymer App Toolbox template. 

- `my-app.html` contains a configured `<firebase-app>` component.
- `my-models.html` (which is a page configured in `my-app.html` routes) contains a `<add-model>` component
- `<add-model>` is a form with a `<firebase-query>`, `<firebase-auth>`, input, and submit button.
-  I attempt to push data using `<firebase-query>` with the following function in the `add-model.html` `Polymer` object:

        Polymer({
            is: 'add-model',
            properties: {
                data: {
                    type: Object
                }
            },
            create: function() {
               this.$.query.ref.push({
                   name: this.$.myModelName.value
                });
            }
        });
### Expected outcome

- Data should push to the query.

### Actual outcome

- Calling `push` on the `<firebase-query>` object in `add-model.html` returns `Cannot read property 'push' of undefined` (in our case it's because `<firebase-app>` does not appear to be properly declared).
- Moving `<firebase-app>` from `my-app.html` to `add-model.html` file does make the `push` function work, but then `my-app.html` loses its Firebase functionality.
- Calling `<firebase-app>` in both my-app.html and add-model.html returns `Uncaught Error: Firebase App named 'firebase-app' already exists.`
- `<firebase-auth>` does work in `add-model.html` and returns a `[[user]]` object.

### Steps to reproduce
1. `polymer init` a full boilerplate from the Polymer App Toolkit
2. Initialize `<firebase-app>` in `my-app.html`
3. Create a `<firebase-query>` component with an input & push function.
4. Add the component to a routed view i.e. `my-view1.html`
5. Try to submit data using the created component

**Comment by Arenari** [comment]
I was having the same problem, try add <link rel="import" href="../bower_components/polymerfire/firebase-query.html"> in my-app.html. That worked for me.

**Comment by marco9446** [comment]
Try to specify the name property in the firebase-app and the app-name property in firebase-query. That solved the problem in my case

**Comment by iadj** [comment]
Solved: http://stackoverflow.com/a/41450672/1250445

Import `polymerfire.html` into the component that contains `firebase-app.html`

**Comment by andrewspy** [comment]
Importing `polymerfire.html` does resolve the issue, but I though we are suppose to only import things that are needed to improve performance on first paint, which `polymerfire.html` does include all firebase elements including `firebase-messaging`, which may not be used by some PWA.

**Comment by FluorescentHallucinogen** [comment]
@cdata, @mbleigh, any response?

IMO, import `polymerfire.html` (even if not all elements from it are needed) is not a good solution.

I have 2 questions:

1. If I import `polymerfire.html` in `my-app.html`, should I import `polymerfire.html` in `my-models.html`?
2. Where should I place `<firebase-auth>` element, in `my-app.html` or in `my-models.html`?
3. Is specify the same `name` property in `<firebase-app>` and `app-name` property in `firebase-query` a solution of the problem?

**Comment by mbleigh** [comment]
What you'll need to do at a minimum is import each of the scripts for the features you want to use before inserting `<firebase-app>` or calling `firebase.initializeApp`. So it might look like a subset of:

```js
<link rel="import" href="bower_components/polymerfire/firebase-app.html">
<link rel="import" href="bower_components/polymerfire/firebase-auth-script.html">
<link rel="import" href="bower_components/polymerfire/firebase-database-script.html">
<link rel="import" href="bower_components/polymerfire/firebase-messaging-script.html">
<link rel="import" href="bower_components/polymerfire/firebase-storage-script.html">
```

So long as you load all of the scripts up front, you shouldn't run into issues later. This needs to be better documented.

**Comment by mbleigh** [comment]
README has been updated with the info above, FWIW.

**Comment by FluorescentHallucinogen** [comment]
@mbleigh Thanks! Any plans to add support of lazy (async) loading Firebase SDK modules?

**Comment by abdonrd** [comment]
👍 about lazy load support! :)
