### ISSUE TITLE
firebase-query not retrieving items

### ISSUE THREAD

**Issue by bkr32** [firebase/polymerfire#178]
### Description
firebase-query does not list items in /notes/ but lists items in /notes/[[user.uid]]

### Expected outcome

should be able to retrieve items from /notes/

### Actual outcome

does not list items in /notes/ but lists items in /notes/[[user.uid/

### Steps to reproduce

working 
```
<firebase-query
    id="query"
    app-name="notes"
    path="/events/[[user.uid]]/"
    data="{{notes}}">
</firebase-query>
```

not working 

```
<firebase-query
    id="query"
    app-name="notes"
    path="/events/schools/comp/"
    data="{{notes}}">
</firebase-query>
```
### Browsers Affected

- [* ] Chrome
- [* ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [* ] Edge
- [ ] IE 11
- [ ] IE 10
other browsers untested

**Comment by christophe-g** [comment]
Seems like a the user do not have access to the path in question (can you have a look at your rules). 
For additional info, activate the log:  
```html
<firebase-query 
  log 
  id="query" 
  ...
></firebase-query>
```

**Comment by bkr32** [comment]
thanks for the reply @christophe-g  i turned the database rules to public just in case the user didn't have access, just a side note but i am able to fetch that path on the android app with the same user 

as for the log it returns 

`Initializing stored value.`

thanks

**Comment by phidias51** [comment]
@bkr32 I'm having the same problem. Are you getting a warning about _flattenBehaviorsList? 
[firebase-query::_flattenBehaviorsList]: behavior is null, check for missing or 404 import

**Comment by bkr32** [comment]
@phidias51  i too have a variation of that warning `[my-app::_flattenBehaviorsList]: behavior is null, check for missing or 404 import` i have no clue as to what is missing or hasn't been imported

**Comment by bkr32** [comment]
it seems `firebase-query` simply wont fetch any items from a path without `[[user.uid]]` i've tried binding any response and sending it to php to query my registration ID's and send notifications to those but without this im pretty stuck,
any suggestions @christophe-g 

thanks

**Comment by christophe-g** [comment]
Oh, right - you indeed need to have `[[user.id]]` resolved for a path like `/events/[[user.uid]]/`. Otherwise, your path will be stamped as not ready and the related firebase element will not fetch any data. 
See: 
```js
__pathReady: function(path) {
        return path && path.split('/').slice(1).indexOf('') < 0;
      },
```
If you want to fetch at `/events`  use it as your path. 
C.

**Comment by phidias51** [comment]
I've found a few reasons that this might occur:

The firebase-app tag was specified improperly. If the firebase console
would generate a tag instead of a JavaScript snippet, this could be avoided.

The firebase-auth tag was specified improperly. Check the app name to make
sure it agrees with the firebase-app tag.

The security rules for the node you're trying to access don't agree with
the account that you're using.

The CORS plugin in chrome was interfering with communication with the
firebase database.

I "dropped" the firebase database and re-created it (along with the whole
app), but that hasn't fixed the problem yet.

Mark

**Comment by bkr32** [comment]
using `/notes` fixed my issue thanks @christophe-g
