### ISSUE TITLE
Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined && Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by ayush-bhandari** [firebase/polymerfire#183]
# I am stuck at "Build a Progressive Web App with Firebase, Polymerfire and Polymer Components" codelabs STEP 22. 

I am a learning developer so I am not sure what's going on. (hence, the title too)
I keep getting these errors:
![screen shot 2017-02-23 at 4 35 40 pm](https://cloud.githubusercontent.com/assets/19263360/23256173/79c2e560-f9e6-11e6-92e4-25684000429e.png)

I was getting first three errors from few steps earlier but I ignored it.
And Now I am getting this fourth error : "**Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined**", then I started looking for solutions. I already read these two solutions 
[https://github.com/googlecodelabs/feedback/issues/34](https://github.com/googlecodelabs/feedback/issues/34)
[https://github.com/googlecodelabs/feedback/issues/38](https://github.com/googlecodelabs/feedback/issues/38)

but nothing worked, I don't know why.

My **index.html** `is:`
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
    <title>Note App</title>
    <link rel="manifest" href="manifest.json">
    <!-- Older Chrome configuration -->
<meta name="mobile-web-app-capable" content="yes">
<meta name="application-name" content="Notes">
<link rel="icon"
      sizes="192x192"
      href="bower_components/note-app-elements/images/icon-4x.png">
    <style>
      body {
        margin: 0;
      }
    </style>
<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<script src="bower_components/web-animations-js/web-animations.min.js"></script>
<link rel="import" href="bower_components/platinum-sw/platinum-sw-elements.html">
<link rel="import" href="bower_components/polymerfire/firebase-app.html">
<link rel="import" href="note-app.html">
</head>
  <body>
  <platinum-sw-register
    auto-register
    skip-waiting
    clients-claim
    reload-on-install
    href="sw-import.js">
  <platinum-sw-cache
      default-cache-strategy="networkFirst">
  </platinum-sw-cache>
</platinum-sw-register>
<firebase-app 
        name="note-app" 
       api-key="<my-api-key>" 
       auth-domain="<auth-domain-url>" 
       database-url="<database-url>">
</firebase-app>
<note-app></note-app>
</body>
</html>
```

My **sw-import.js** is:
`importScripts('bower_components/platinum-sw/service-worker.js');`

My **note-app.html** is:
```
<link rel="import" href="bower_components/note-app-elements/na-elements.html">
<link rel="import" href="bower_components/app-storage/app-indexeddb-mirror/app-indexeddb-mirror.html">
<link rel="import" href="bower_components/polymerfire/polymerfire.html">

<dom-module id="note-app">
  <template>
    <style include="note-app-shared-styles"></style>
    <na-toolbar></na-toolbar>
<na-login on-sign-in="signIn"
    signed-in="[[signedIn]]"
    disabled="[[!online]]">
    	
    </na-login>
<firebase-auth
    id="auth"
    app-name="notes"
    provider="google"
    signed-in="{{signedIn}}"
    user="{{user}}">
</firebase-auth>
  </template>
  <script>
    Polymer({
      is: 'note-app',

    behaviors: [Polymer.NoteAppBehavior],
    signIn: function() {
      this.$.auth.signInWithPopup();
    }
    });
  </script>

</dom-module>
```

My **manifest.json** is:
```
{
  "name": "Notes",
  "scope": "./",
  "start_url": "index.html",
  "display": "standalone",
  "orientation": "any",
  "theme_color": "#9C27B0",
  "background_color": "#9C27B0",
  "icons": [{
    "src": "bower_components/note-app/common/images/icon-0-75x.png",
    "sizes": "36x36",
    "type": "image/png"
  },
  {
    "src": "bower_components/note-app/common/images/icon-1x.png",
    "sizes": "48x48",
    "type": "image/png"
  },
  {
    "src": "bower_components/note-app/common/images/icon-1-5x.png",
    "sizes": "72x72",
    "type": "image/png"
  },
  {
    "src": "bower_components/note-app/common/images/icon-2x.png",
    "sizes": "96x96",
    "type": "image/png"
  },
  {
    "src": "bower_components/note-app/common/images/icon-3x.png",
    "sizes": "144x144",
    "type": "image/png"
  },
  {
    "src": "bower_components/note-app/common/images/icon-4x.png",
    "sizes": "192x192",
    "type": "image/png"
  }]
}
```
And my folder structure is: 
![screen shot 2017-02-23 at 4 54 44 pm](https://cloud.githubusercontent.com/assets/19263360/23256714/d077fa24-f9e8-11e6-9e2b-79e3524f866f.png)

**Comment by anisayr** [comment]
Your firebase-app  and firebase-auth have a different name tag, this bug may come from here.
Can you try this following modification ? 
`<firebase-app 
        name="notes" 
       api-key="<my-api-key>" 
       auth-domain="<auth-domain-url>" 
       database-url="<database-url>">
</firebase-app>`

**Comment by ayush-bhandari** [comment]
still getting the same error.

**Comment by jayakusuma13** [comment]
Hey, are you doing the google dev polymer firebase tutorial? I just did the exact same thing.

Have you tried to put the firebase-auth above the toolbar ?
By the way, this is my code, it's working well.

`<link rel="import" href="bower_components/note-app-elements/na-elements.html">
<link rel="import" href="bower_components/app-storage/app-indexeddb-mirror/app-indexeddb-mirror.html">
<link rel="import" href="bower_components/polymerfire/polymerfire.html">


<dom-module id="note-app">
  <template>
    <style include="note-app-shared-styles"></style>
    <firebase-auth
        id="auth"
        app-name="notes"
        provider="google"
        signed-in="{{signedIn}}"
        user="{{user}}">
    </firebase-auth>
    <na-toolbar
    signed-in="[[signedIn]]"
    on-sign-out="signOut">
    </na-toolbar>
    <na-login
    on-sign-in="signIn"
    signed-in="[[signedIn]]"
    disabled="[[!online]]">>
    </na-login>

    <paper-fab
        icon="add"
        on-tap="create"
        disabled="[[!online]]"
        aria-label="Add note">
    </paper-fab>

    <na-editor
        id="editor"
        app-name="notes"
        note="{{editableNote}}"
        on-close="commitChange">
    </na-editor>

    <firebase-document
        id="document"
        app-name="notes"
        path="[[editableNoteId]]"
        data="{{editableNote}}">
    </firebase-document>

    <firebase-query
        id="query"
        app-name="notes"
        path="/notes/[[user.uid]]"
        data="{{notes}}">
    </firebase-query>

    <app-indexeddb-mirror
        session="[[user.uid]]"
        key="notes"
        data="{{notes}}"
        persisted-data="{{persistedNotes}}">
    </app-indexeddb-mirror>

    <div class="notes">
      <template is="dom-repeat" items="[[persistedNotes]]" as="note">
        <na-note
          id$="[[note.$key]]"
          title="[[note.title]]"
          body="[[note.body]]"
          on-tap="edit">
        </na-note>
      </template>
    </div>

  </template>
  <script>
    Polymer({
      is: 'note-app',
      behaviors: [Polymer.NoteAppBehavior],
      signIn: function(){
        this.$.auth.signInWithPopup();
      },
      get notesPath(){
        return '/notes/' + this.user.uid;
      },
      toEditableId: function(noteId){
        return this.notesPath + '/' + noteId;
      },
      get isEditable(){
        return this.online;
      }
    });
  </script>
</dom-module>
`

**Comment by ayush-bhandari** [comment]
Well, I was able to solve "Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined" error but I am still getting "Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope'" . I tried putting firebase-auth above toolbar but it didn't work out. Thanks anyway though.

**Comment by gmlnchv** [comment]
@ayush-bhandari how did you solve the "Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined" thing?

**Comment by gmlnchv** [comment]
Try with the `2.0-preview` branch https://github.com/firebase/polymerfire/tree/2.0-preview

**Comment by ayush-bhandari** [comment]
"Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope'" didn't stopped me from completing codelabs although I wasn't able to figure out that error and with 2.0-preview branch I didn't get any errors. So, I will close this issue. Thanks!!
