### ISSUE TITLE
Add sort-direction to query

### ISSUE THREAD

**Issue by phidias51** [firebase/polymerfire#190]
Currently, there's no way to set the sort direction for the results of a query.  For example, if you have a recommendation engine that scores a series of matches, and you order-by-child="score", the results are sorted from lowest to highest -- which isn't very useful for a user. A **sort-descending** flag, or a **sort-direction** attribute would make this much easier to deal with than trying to apply sorting on the client side.

**Comment by justweb1** [comment]
If you need the results to be descending run it through a simple calculated field.
### Inside your dom-repeat template
```html
items$="{{_descending(data)}}" as="item"
```
### Inside the script tag under your properties
```js
_descending: function(data) {
  return data.reverse();
},
```

**Comment by phidias51** [comment]
The problem is that you're doing that work on the client when it should be
done on the server. Likewise, filtering should be done on the server.

**Comment by mbleigh** [comment]
The Firebase Realtime Database does not have descending order queries. A
calculated field or filter is the correct way to do this.

**Comment by justweb1** [comment]
This post is on the polymerfire repo so it is all client-side. it can also be done server side with a firebase function.

**Comment by phidias51** [comment]
Given that polymerfire depends on the firebase javascript library, which in turn depends on the firebase real-time database, change requests to the polymerfire components would likely affect both the library and the database. Since there is no way to track change requests against the database itself, I rely on Googlers passing along these type of requests to the appropriate maintainer(s).

**Comment by mbleigh** [comment]
You shouldn't. There's a feature request form:
https://firebase.google.com/support/contact/bugs-features/ that is tracked
and funneled to the appropriate teams. There's no public tracker but the
feature request form is going to get your request to the right people.

GitHub issues should only be relevant to the specific repo.

**Comment by phidias51** [comment]
I've tried that on a number of occasions. However, it's sort of a black hole. You report things, and you never hear about status changes to your change requests. So you never know if something is being worked on, or simply dropped altogether.

**Comment by mbleigh** [comment]
Sorry to hear that's been your experience -- I'll pass that along as feedback to the team. However, that's still the best and most appropriate way to make feature requests.

**Comment by iSuslov** [comment]
Gentlemen, please check this pull request.  
https://github.com/firebase/polymerfire/pull/348
