### ISSUE TITLE
firebase-app : Return error if mandatory attributes not set

### ISSUE THREAD

**Issue by vorcigernix** [firebase/polymerfire#20]
### Expected outcome

Firebase app element should return error with warning that required attribute is not set (or is mistyped).
### Actual outcome

Element will return friendly warning, like "required parameter api-key is not set"
### Browsers Affected
- [X] Chrome
- [X] Firefox
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

**Comment by tjmonsi** [comment]
Given that this is over 1 year without any activity, Let's close this for now. Please feel free to re-open this if this is still not working.
