### ISSUE TITLE
Polymerfire#2.0 breaks paper-inputs

### ISSUE THREAD

**Issue by colincannon-acp** [firebase/polymerfire#202]
### Description

When using the polymer 2.0 start kit.  Installing polymerfire#2.0-preview causes paper-input to break and log console errors when rendered.
### Expected outcome
The paper-input element should not be affected by simply bower installing polymerfire#2.0-preview.

installing polymerfire#2.0-preview causes the paper-input to render with the label broken and causes a slew of console errors.
### Steps to reproduce

1.  Polymer init a start kit 2.0
2.  bower install paper-input#2.0-preivew
3.  Add the paper-input anywhere in your new start kit
4.  bower install polymerfire#2.0-preview
5.  paper-input render with the label under the input and when you click on the paper-input, console errors from paper-input-container occur

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by e111077** [comment]
Heya, I can't seem to replicate this issue. Can you give it another try with master (which is 2.0.0) and see if this is still an issue?

**Comment by colincannon-acp** [comment]
Updating to 2.0.0 solved the issue
