### ISSUE TITLE
Auth error attempting sign-in offline

### ISSUE THREAD

**Issue by fafcrumb** [firebase/polymerfire#209]
### Description
Calling either `signInWithRedirect()` or `signInWithPopup()` while offline will throw the expected error `O {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."}`. However, returning online and calling `signInWithRedirect()` or `signInWithPopup()` again will throw the same error. Any attempt to call these functions afterwards results in the same error unless the browser is refreshed.

### Expected outcome

Auth sign-in functions normally after coming back online

### Actual outcome

Auth sing-in throws an error and continues to do so on any following attempts

### Steps to reproduce

1. Go offline
2. Call either `signInWithRedirect()` or `signInWithPopup()` (error should be logged here: `O {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."}`)
3. Go online
4. Call either `signInWithRedirect()` or `signInWithPopup()` (same error occurs on every sign-in attempt

### Browsers Affected

Tested on chrome and safari 10
- [ x] Chrome
- [ x] Safari 10

**Comment by mbleigh** [comment]
This is not a PolymerFire issue but an issue with the Firebase SDK. Please [file a bug](https://firebase.google.com/support/contact/bugs-features/) there.

**Comment by gaurav414u** [comment]
@fafcrumb Did you find any solution to this?

**Comment by fafcrumb** [comment]
@gaurav414u My current workaround looks like this:
```
const auth = this.$.auth;
auth.refreshNetworkStatus();
if (auth.online)
  auth.signInWithRedirect();
```
So just a paranoid check if we're online before trying to sign in.
