### ISSUE TITLE
Multiple firebase-query share same data array

### ISSUE THREAD

**Issue by alejoberardino** [firebase/polymerfire#21]
### Description

Somehow when using more than one firebase-query elements the data array is the same for both of them, with what should be the first array and the second concatenated one after the other.

### Expected outcome

Using two firebase-query elements with different paths bound to separate arrays, results in two different and independent data sets.

### Actual outcome

Using two firebase-query elements with different paths bound to separate arrays a1 and a2, results in a1 being equal to a2 where their value is the concatenation of both expected data sets.

### Steps to reproduce

1. Put a firebase-appand a firebase-auth element in the page.
2. Put two firebase-query elements on the page, with different paths and bound to different arrays.
3. Check both values

**Comment by cdata** [comment]
Hi, thanks for reporting. Could you please provide the code for a repro condition? It doesn't have to be live, just something that we can use to see how you have set it up.

**Comment by alejoberardino** [comment]
Sorry for the delay, I checked again today in a clean app with the latest version and couldn't reproduce. Thanks anyway

**Comment by mgibas** [comment]
Very similar issue here: when I have firebase query for ie. `/foos` and then I'm trying to query some children ie. `/foos/1/bars` and I change children query path (getting children from other `foo`) to i.e. `/foos/2/bars` my data is overwritten with empty array. This is not happening for not nested paths.

[jsbin](http://jsbin.com/fopihaweve/1/edit?html,console,output)

removing `firebase-query` with `path="/foos"` eliminates issue.
