### ISSUE TITLE
Difference between {{ }} and [[ ]]

### ISSUE THREAD

**Issue by jomajoms** [firebase/polymerfire#218]
What is is the difference between {{}} and [[]]. Thank you very much.

**Comment by kownacki** [comment]
https://www.polymer-project.org/2.0/docs/devguide/data-system#data-flow-control

**Comment by jomajoms** [comment]
Thank you

**Comment by kownacki** [comment]
@jomajoms Now that you have your problem solved, can you close this issue?

**Comment by jomajoms** [comment]
ohh sorry, I am new to Github and I don't know about it :) thank you for
reminding.
