### ISSUE TITLE
firebase-query element can't process an array to process it

### ISSUE THREAD

**Issue by jperera84** [firebase/polymerfire#229]
### Description

I"m using the element `firebase-query` to interact with Firebase Realtime Database, but I'm having issues to get the list. The feature that I'm trying to implement is that I need to get from Firebase Database the List of Categories, but I need to process that list before to use a `dom-repeat` template to stamp an element on the page.
To solve that I tried to use an observer in the category property. This is the element that I created:

```
       <firebase-query
            id="query"
            path="/Categories"
            data="{{categories}}">
        </firebase-query>
        <template is="dom-repeat" items="{{categories}}" as="cat">
            <div class="container">
                <span class="text-subtitle">[[cat.name]]</span>
                <div class="card-container">
                </div>
            </div>
        </template>
    </template>

    <script>
        class MyMainCategories extends Polymer.Element {
            static get is() { return 'my-maincategories'; }
            static get properties() {
                return {
                    categories:{
                        type: Object,
                        notify: true,
                        value: function() { return []; },
                        observer: '_dataChanged'
                    }
                };
            }
            constructor() {
                super();
            }
            ready() {
                super.ready();
                Polymer.RenderStatus.afterNextRender(this, function() {
                });
            }
            _dataChanged () {
                // do something when the query returns values
                if(this.categories.length > 0){
                    console.log("Now it change");
                }
            }
        }
        window.customElements.define(MyMainCategories.is, MyMainCategories);
    </script>
```

### Expected outcome

At the moment where the property `categories` get values the `console.log("Now it change");` should be appear on the console. 

### Actual outcome

The `query` object is working because I was able to stamp the categories on the page with the `dom-repeat` template.
But the observer method: `_dataChanged ` is fire actually twice but debugging this method I was not able to get never the `categories` array with values, that's why I could not process the list.

### Browsers Affected

- [x ] Chrome

**Comment by mbleigh** [comment]
What if instead you do:

    observers: ['_categoriesChanged(categories.*)']

In your element?

**Comment by jperera84** [comment]
Thanks @mbleigh I tested that option but I got a call to my method for every item in my list and I don't think it is very useful , why is not way to get when all the query is being execute?

**Comment by mbleigh** [comment]
The query is updated for each individual item that changes -- that's how
the Realtime Database works.

**Comment by jperera84** [comment]
I think could be useful to create some transaction attribute that allow you to get a promise when the query finish to fill the property. Thanks

**Comment by mbleigh** [comment]
By design, the Realtime Database has no concept of "finished" for a
listener/query -- it simply receives data and continually updates state.
