### ISSUE TITLE
OAuth with polymer-2-starter-kit in Chrome

### ISSUE THREAD

**Issue by ctinute** [firebase/polymerfire#237]
### Description

Method `signInWithPopup()` and `signInWithRedirect()` return error:

> auth/network-request-failed: A network error (such as timeout, interrupted connection or unreachable host) has occurred.

on Chrome **but working fine on MS Edge**.

- My project was modified from polymer-2-starter-kit
- Other sign in methods work fine
- I have not tested with other OAuth provider yet but Google

### Expected outcome

Popup Google OAuth sign in page.

### Actual outcome

Google OAuth sign in page (about:blank) popup but showing nothing and closing after some seconds.
Log: 

> Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'page404'. The type name is invalid.
>     at window.Polymer (https://dkmh-spkt.firebaseapp.com/src/my-app.html:18:1504)   
>     at https://dkmh-spkt.firebaseapp.com/src/page404.html:15:11

> Uncaught Error: Network Error
>     at firebase-auth.js:156

### Live Demo
https://dkmh-spkt.firebaseapp.com/view1

### Steps to reproduce

1. Clone polymer-2-starter-kit project with `polymer init` command
2. Install polymerfire via `bower install --save firebase/polymerfire`
3. Modify src/my-view1.html as [this](https://github.com/ectn/dkmh-polyfire/blob/lightedit/src/my-view1.html)
4. Run with `polymer serve --open` command
5. Click View One in menu drawer if you're on another page
6. Choose Sign in With Google

### Browsers Affected

- [x] Chrome
- [ ] Firefox not tested
- [ ] Safari 9 not tested
- [ ] Safari 8 not tested
- [ ] Safari 7 not tested
- [ ] Edge
- [ ] IE 11 not tested
- [ ] IE 10 not tested

**Comment by tjmonsi** [comment]
This is weird. I tried using Google Chrome and it is working fine.

**Comment by ctinute** [comment]
@tjmonsi checked, now it works. I haven't modify anything since.
