### ISSUE TITLE
equalTo Property Type

### ISSUE THREAD

**Issue by JGSolutions** [firebase/polymerfire#243]
Not understanding why equalTo property is an object in the firebase-query component.

` equalTo: {
            type: Object,
            value: null
          },`

trying to do this
`    <firebase-query
      path="/accounts"
      order-by-child="type"
      equal-to="re"
      data="{{accounts}}">
    </firebase-query>`

and the value is undefined

If I change to {type: String} then it works.

**Comment by JGSolutions** [comment]
More investigation and it seems it works only with Boolean values? But property type is an Object? So string goes not work unless switching it to a String type

**Comment by tjmonsi** [comment]
equalTo works for us with using String. I like to see what's the database though, because it might be because there's no attribute "type" that has a value "re"

**Comment by JGSolutions** [comment]
@tjmonsi So I got back to this functionality and began fooling with the data because I need to create a feature to filter the data depending on the option that the user selects.

My data is very very simple
![data](https://user-images.githubusercontent.com/197318/34536018-e81cebf8-f091-11e7-9f19-e6ebefa0e8da.jpg)

So I use firebase-query doesn't work:
`    <firebase-query
     id="ref"
     app-name="chowdashi"
     data="{{orders}}"
     order-by-child="status"
     equal-to="new"
     path="/storeFrontOrders/[[authId]]">
    </firebase-query>
`

Then I use the native firebase way and it works!:

`
ref.child('/storeFrontOrders/Etfo0ldGiih5pSw0rR1XUWIpGLA2').orderByChild('status').equalTo('new').on('value', function (articleData) {
              console.log(articleData.val())
            })
`

Not sure how polymerfire handles filtering data with order-by-child or equal-to. Did research and the only thing i get is "Restructure your data" NOPE. Not a good response.

Not sure how this polymerfire lib is going. There hasn't been an update since Oct 2. Issues are just accumulating. Good features are missing like firestore and authentication by telephone. I know these are fairly new features but the community has been great submitting pull requests and why haven't they been pushed?

This lib is way too basic and most of the time I am referencing the actual firebase methods unless the data is simple then I will go ahead with firebase-document or firebase-query.

**Comment by merlinnot** [comment]
Hi, I’m contributing mainly to the firestore mixin, but I might be able to help you with this one. Could you please provide me with a minimal reproduction of this issue? I’ve just checked everything and it works as expected, there are some gotchas tho. Are you making this query on numbers?

**Comment by JGSolutions** [comment]
@merlinnot I been seeing all your pull requests and great work. 

Back to my issue not sure why this code does not work according to the data structure above. I just want to pull all data where status property is equal to 'new'

`<firebase-query id="ref" app-name="chowdashi" data="{{orders}}" order-by-child="status" equal-to="new" path="/storeFrontOrders/[[authId]]"> </firebase-query>`

**Comment by merlinnot** [comment]
I’ll take a closer look tomorrow afternoon (UTC). If you could write a simple snippet in some test project which represents the issue, that would help a lot. Otherwise I’ll have to do it myself and I might not have that much time.

**Comment by JGSolutions** [comment]
A bit complicated to provide a snippet code because user needs to be authenticated etc. The only thing I want to do is call the firebase-query and pull all data where status is equal to 'new' 


In the firebase-query code the equalTo prop is set as an object

`          equalTo: {
            type: Object,
            value: null
          },
`
Does it need to be an object? If I set it as a string it will work

`          equalTo: {
            type: String
          },
`

Here is another weird piece of code on line 158. A method with same arguments? I am sure there is a reason for this as I read through the method but at first it was weird.

`        attached: function() {
          this.__queryChanged(this.query, this.query);
        },
`

I am closing it as it seems that this will never be fixed or improved.

**Comment by merlinnot** [comment]
Type of the property is correct. In js 'everything is an Object'. Since you can use Booleans, Numbers, Strings etc. as values of this property, the most reasonable thing to do is to define its type as an Object.

I've just tested this myself and it works. You don't have to give anyone access to your project, just create a new one (it's free!) and a simple Polymer app (few lines of code) which uses `firebase-query` with `equal-to` property and **doesn't** work.
