### ISSUE TITLE
Link email and password to anonymous account from within polymer

### ISSUE THREAD

**Issue by dshukertjr** [firebase/polymerfire#247]
Here is the official documentation of how to link email and password to an existing anonymous login account.

https://firebase.google.com/docs/auth/web/anonymous-auth

Following the instructions, first I need to do this:

```var credential = firebase.auth.EmailAuthProvider.credential(email, password);```

which I have no way of doing with polymer, because I do not have access to the global firebase variable. How do I get a credential using polymer?  

How do I access the "firebase" variable from within polymer?

**Comment by tjmonsi** [comment]
Actually you can... try typing firebase in the console and you can access it

**Comment by dshukertjr** [comment]
In the console I could call it, but when I call it within a method of my elements, like this:

```
      signup(){
        console.log(firebase)
      }

```
I get "undefined"
