### ISSUE TITLE
Firebase Auth : SignInWithPopup and Standalone mode

### ISSUE THREAD

**Issue by Oupsla** [firebase/polymerfire#269]
### Description
The method signInWithPopup doesn't work when the application is launched in standalone mode (when the web-app is added to the user screen and launch from there).

### Expected outcome
The standalone app launch a new pop-up (regardless of a browser is opened or closed) and after authentication, the user is logged in.

### Actual outcome
1st Case : There is no browser opened (using Chrome v.60 on my Android v.6.0.1), the standalone app launches a browser and opens a window so the user can log in, but the standalone app don't wait and returns to the foreground (without user logged in). The only solution for the user is to re-open the browser manually so the connexion can be finished.

2nd Case : A browser is active, nothing happens... And after an other action is made, the error function is triggered with the error code 'auth/cancelled-popup-request'

### Live Demo
I made a minimal demo available here : https://testloginfire.firebaseapp.com/
The repo here : https://github.com/Oupsla/FirebaseAuth-Standalone

I have init this repo with the command `polymer init` and select the prpl example.

### Steps to reproduce

1. Create a new polymer project (prpl for example).
2. Add firebase-app and firebase-auth (with good credentials) and with a button that trigger signInWithPopup method
3. Build (es6-unbundled preset but no js minify, cause of issue with minify and firebase lib) and deploy this app somewhere
4. Visit the app with an Android phone and install it on home screen
5. Launch the app with the homescreen icon (standalone mode)
6. Try to connect...

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by tjmonsi** [comment]
I think on Chrome 58 it is working. I updated my Chrome 58 to Chrome 60 and cannot replicate the whole error on the phone (meaning I got logged in).

I am currently testing it with an LG G3. 

Going to check it again.

**Comment by Oupsla** [comment]
I dont know if it is related
But now polymer apps are installed like native apps (not like a shortcut) on my phone
Polymer apps are listed in 'All Applications' and you can also see information's about them (like network used, permissions, notification,...) and you can also 'Uninstall' them not only remove the shortcut

Will make a video clip with the problem asap

**Comment by Oupsla** [comment]
![ezgif-4-93eca15663](https://user-images.githubusercontent.com/15279620/30633158-ee626afa-9dea-11e7-96bb-212e2cc9cce9.gif)

**Comment by tjmonsi** [comment]
I see. I also installed your app as a phone application but again it works. If I have time this weekend, I'll fork your repo and look at the code and add an error catching mechanism to see if there are any errors showing up in the console and will look from there.

Thanks

**Comment by Oupsla** [comment]
Seems to work now, was maybe an issue with Android Chrome
