### ISSUE TITLE
Add a 'bower install' line.

### ISSUE THREAD

**Issue by WaverleyDesign** [firebase/polymerfire#27]
It'd be really helpful to get this element registered on Bower - the 'bower install' command listed during Michael Bleigh's Google IO talked errored for me.

**Comment by bvhme** [comment]
`bower install polymerfire --save` worked for me! Otherwise you can try `bower install firebase/polymerfire --save`

**Comment by maria-le** [comment]
@bvhme: Do not use `bower install --save polymerfire` because that points to an outdated version.

Instead, use `bower install --save firebase/polymerfire`
