### ISSUE TITLE
Firestore: consistent names of the options

### ISSUE THREAD

**Issue by merlinnot** [firebase/polymerfire#286]
Names of `doc` and `collection` options of the `firestore(Element|Mixin)` are inconsistent. I think we should change this somehow. I'd pick one of these:
1. Change `doc` to `document`
2. Merge `doc` and `collection` into one option, i.e. `firestorePath`

**Comment by tjmonsi** [comment]
I think we should still use `doc` given that it is being used in the JS spec?

**Comment by mbleigh** [comment]
Please keep consistent with the official SDK

**Comment by merlinnot** [comment]
Ok.
