### ISSUE TITLE
Documentation: explain why <firebase-query> does not support primitives as values

### ISSUE THREAD

**Issue by axacheng** [firebase/polymerfire#29]
Not quite sure the firebase-query.html is ready for production. Because I've played it around but I found the error when I tried to query a simple structure. Note, it works great in firebase CLI and angularjs but not polymerfire.

```javascript
Error:
index.js:362 Uncaught TypeError: Cannot create property '$key' on string '2016'
index.js:362 Uncaught TypeError: Cannot create property '$key' on string 'Eng'
index.js:362 Uncaught TypeError: Cannot create property '$key' on string 'EMPLOYEE'
```

Here is my markup for very simple fetch:
```html
<firebase-query
    app-name="teams-prod"
    path="/team/members"
    data="{{data}}">
</firebase-query>
<p>{{ data }} </p>
```

```bash
shell> firebase database:get --project project-133684xxxx /team/members
{"axa":{"checkin":"2016", "type":"EMPLOYEE", "team":"Eng"}}
```

**Comment by 43081j** [comment]
I get the same issue. In the older elements, this happened:
https://github.com/GoogleWebComponents/firebase-element/blob/master/firebase-collection.html#L500

An explicit check for it being an `Object` or not.

As you can see there's no such equivalent in polymerfire:
https://github.com/firebase/polymerfire/blob/master/firebase-query.html#L287

**Comment by axacheng** [comment]
I added one more layer (called:profile) on my json schema (tree) then this problem went away.

```javascript
**Original one**
{
  "members" : {
    "axa" : {
        "checkin" : "2016"
      }
    }
  }
}

**New one**
{
  "member" : {
    "axa" : {
      "profile" : {
        "checkin" : "2016"
      }
    }
  }
}


```

**Comment by 43081j** [comment]
Technically, you can probably use a `firebase-document` rather than `firebase-query` for an array of primitives to get around this issue, too.

**Comment by cdata** [comment]
@axacheng Yes, `firebase-query` does not support primitives as values. This needs to be communicated better. I am changing the title of this issue to better reflect that.

**Comment by mbleigh** [comment]
#96 should address this by supporting leaf nodes as `$val` in the returned data. Thoughts?

**Comment by 43081j** [comment]
Looks good to me, very similar to what the older firebase elements did. Should fix this issue fine :)
