### ISSUE TITLE
Build a GeoFire Element

### ISSUE THREAD

**Issue by RobinLinus** [firebase/polymerfire#3]
It would be nice to have a GeoFire Element for declarative realtime location queries with Firebase. 
Currently it is unnecessarily complicated to combine the imperative GeoFire API with the declarative element APIs.

**Comment by cdata** [comment]
That sounds cool. Let's do it.

**Comment by mbleigh** [comment]
I'm definitely in favor of building this out, but I'm hesitant to add more dependencies to PolymerFire that make it more heavyweight. Might make more sense to create e.g. `polymerfire-geo` as a separate repo.

**Comment by mbleigh** [comment]
I'm going to close this as *will not implement in PolymerFire main repo, but hope that someone builds it or that I have time to someday*.

**Comment by stillgbx** [comment]
If anyone is interested, I've started this: https://github.com/stillgbx/polymerfire-geo

**Comment by chwzr** [comment]
Why there is no implementation of it? 
It would be a blast having a geofire element.  
Please Re-Open it, since saying "oh i do not want to add more dependencies, because i want to keep it lightweight " is not solving the issue. 



# **Geo-queries are fundamental nowadays!**

**Comment by christophe-g** [comment]
@chwrz - the nice thing about Open Source Libraries like this one (to which people often contribute out of their extra time freely) it that nothing prevents submission of a PR with code/features one's need.
Best,
C.

**Comment by mbleigh** [comment]
I'm not interested in expanding the dependencies of this library beyond the
core firebase sdks.

**Comment by FluorescentHallucinogen** [comment]
See https://webcomponents.org/element/jifalops/geo-query :wink:

**Comment by FluorescentHallucinogen** [comment]
See also https://webcomponents.org/element/jifalops/geo-query-input.
