### ISSUE TITLE
Polymer service workers breaking firebase-auth

### ISSUE THREAD

**Issue by felipecesar00** [firebase/polymerfire#309]
### Description
When try to login through facebook, google or email authentication it doesn't open the login popup and returns network error: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
The login works fine on localhost and stops working when I deploy to hosting. If I deactivate the Service Worker generation on "polymer.json" it works fine on hosting too. The problem only appears when I deploy my app with the service worker generated by "polymer build"

Here, my polymer.json:
`
{
  "entrypoint": "index.html",
  "shell": "src/app-shell.html",
  "sources": [
    "src/**/*",
    "images/**/*"
  ],
  "extraDependencies": [
    "manifest.json",
    "bower_components/webcomponentsjs/*.js"
  ],
  "lint": {
    "rules": ["polymer-2"]
  },
  "builds": [{
    "bundle": true,
    "js": {"compile": true, "minify": false},
    "css": {"minify": true},
    "html": {"minify": true},
    "addServiceWorker": false,
    "sourcemaps": false,
    "insertPrefetchLinks": true
  }]
}

### Expected outcome
When user clicks on "login by facebook" or "login by google" opens an login modal that allows user to enter his email and password according to the provider chosen

### Actual outcome
It doesn't open the login modal and returns the networking working: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by mbleigh** [comment]
You need to exclude the `/__/**` namespace from the navigation fallbacks of your service worker. Firebase Auth uses special paths on your `firebaseapp.com` domain to load authentication widgets, etc.

**Comment by felipecesar00** [comment]
ok. Thanks :)
