### ISSUE TITLE
`getStoredValue` attempts to resolve a duplicated/incorrect path

### ISSUE THREAD

**Issue by 43081j** [firebase/polymerfire#32]
I'm not sure if this is a bug or expected behaviour, but say I have the following:

```html
<firebase-document path="/foo" data="{{foo}}"></firebase-document>
```

This works fine, as expected. However, I noticed that [getStoredValue](https://github.com/firebase/polymerfire/blob/master/firebase-document.html#L158) is hit in a strange way.

You can see it calls `this.ref.child(path)`. In my case, `path` is `/foo` _but_ `this.ref` is **already** `xyz.firebaseio.com/foo` so it tries to resolve `/foo/foo`. Surprisingly, this doesn't seem to affect anything, `foo` is still set correctly, but it definitely looks wrong still.

**Comment by mraerino** [comment]
May have connections to #18

**Comment by Mayhem50** [comment]
I see the same behavior. My ref is set to path so call `this.ref.child(path)` calls  `foo/foo`. Unlike 43081j, it doesn't work fine for me. To resolve it I had to remove `.child(path)`

**Comment by e111077** [comment]
It seems as if the code is duplicating the path. The listener callback returns null every time on initialization.
