### ISSUE TITLE
polymer-cli will not build with polymerfire included in project

### ISSUE THREAD

**Issue by craftyc0der** [firebase/polymerfire#34]
This error prevents the building of an bundled package. 
Reproduce by adding polymerfire to bower.json
`"polymerfire": "firebase/polymerfire#^0.9.2",`
Error:
> ```
debug:   no file for ../bower_components/firebase-sdk/index.js :(
debug:   No file found for ../bower_components/firebase-sdk/index.js
debug:   no file for ../bower_components/promise-polyfill/Promise.js :(
debug:   No file found for ../bower_components/promise-polyfill/Promise.js
debug:   no file for ../bower_components/promise-polyfill/Promise-Statics.js :(
debug:   No file found for ../bower_components/promise-polyfill/Promise-Statics.js
error:   Promise rejection: Error: no resolver found for ../bower_components/firebase-sdk/index.js
error:   Error: no resolver found for ../bower_components/firebase-sdk/index.js
```

**Comment by cdata** [comment]
@justinfagnani can you comment on the likely cause of this problem?

**Comment by craftyc0der** [comment]
My apologies. This is related to a bad build file for the polymer-cli. Adding Firebase appeared the proximate cause but I was in error. Thank you for your efforts!
