### ISSUE TITLE
signInWithCustomToken and just puzzled about ploymerfire's direction.

### ISSUE THREAD

**Issue by johnlim** [firebase/polymerfire#35]
Hi,

Will signInWithCustomToken be supported?  Also, will there be something similar to `<firebase-collection>`? 

I'm currently using the 'official' firebase elements, https://elements.polymer-project.org/elements/firebase-element and am wondering what is status and direction with polymerfire. Will it eventually replace the original firebase-element?

Thanks.

**Comment by 43081j** [comment]
You can use `signInWithCustomToken` via the auth reference directly:

```html
<firebase-auth id="foo"></firebase-auth>
<script>
...
this.$.foo.auth.signInWithCustomToken(token);
...
</script>
```

Though this definitely does need adding properly.

As for direction, this is for the new Firebase 3 SDK whereas the ones on polymer's website are for version 2. So I presume this will replace them in time.

**Comment by johnlim** [comment]
@43081j thanks for the clarification. Am I right to assume then that current elements like `firebase-collection` will also be included in time?

**Comment by sgammon** [comment]
hi y'all, so i added a pull to include this functionality. please let me know if it needs further work

**Comment by mbleigh** [comment]
Support for this has been added.
