### ISSUE TITLE
No on-firebase-value in firebase-query

### ISSUE THREAD

**Issue by limhenry** [firebase/polymerfire#4]
It would be awesome if there is a listener like `on-firebase-value` in the `firebase-query`. 
This `on-firebase-value` is working in [`GoogleWebComponents/firebase-element/firebase-collection.html`](https://github.com/GoogleWebComponents/firebase-element/blob/master/firebase-collection.html) but not in this Polymerfire repo. 

### Use case
 - Hide the `paper-toast` when the data is loaded.

**Comment by mbleigh** [comment]
Firebase is built around the idea that there's no such thing as "loading" -- once you start receiving child added events you should consider the data live and architect your app as such. Adding a value listener is more expensive and not recommended for collection querying.
