### ISSUE TITLE
<firebase-app> not working with bound attributes

### ISSUE THREAD

**Issue by mraerino** [firebase/polymerfire#42]
### Description
When the `firebase-app` element attributes are bound to some variable, other elements can't get the firebase.App

### Expected outcome

An initialized firebase.App is distributed to all `firebase-*` elements

### Actual outcome

There is no app in the `firebase-*` elements if the attributes are bound.

### Live Demo
http://jsbin.com/layihiyogi/2/edit?html,output

### Steps to reproduce
1. Put a `firebase-app` element without attributes into your document
2. Set element attributes in `attached()`
3. Try getting data out of firebase with a `firebase-document` element

**Comment by mbleigh** [comment]
Working as intended. `<firebase-app>` is an initializer and is not intended to have dynamically bound attributes. Could maybe call this out better in docs.
