### ISSUE TITLE
<firebase-auth> Allowing provider name as input argument for signInWithPopup & signInWithRedirect

### ISSUE THREAD

**Issue by SPrinss** [firebase/polymerfire#44]
### Description
```_attemptProviderSignIn(provider, method)``` provider argument has to be a ```new firebase.auth.providerNameAuthProvider()``` provider instead of the name of the provider.

### Expected outcome
```signInWithPopup(providerName)``` would automatically create a ```new firebase.auth.providerNameAuthProvider()``` using ```_providerFromName``` method.

### Actual outcome
Error: First argument "authProvider" must be a valid Auth provider. (listening to error of firebase-auth)

### Steps to reproduce
this.$.auth.signInWithPopup("google")

**Comment by IvanProdaiko94** [comment]
https://monosnap.com/file/NSJyms9xT76SZrbCjS5KOPYDqa0hPN

**Comment by M-Olivero-WT** [comment]
Hey, i`m not sure which is the solution here, i have the same error treating the 'microsoft.com' provider, just following the instruction of Firebase.

> var provider = new firebase.auth.OAuthProvider('microsoft.com');

I'm just getting the next error: 

![image](https://user-images.githubusercontent.com/74308923/99978124-516d9080-2d84-11eb-8800-f2335f8572d1.png)

was looking others ways to use the provider but.. this is the only available that i found involving microsoft as a provider. 

will be great if you guys have some idea what can i do, or if i'm doing something wrong 😅

**Comment by hoai97nam** [comment]
I just create new instance:
From: `const fbProvider = firebase.auth.FacebookAuthProvider()`
To" `const fbProvider = new firebase.auth.FacebookAuthProvider()`

use react & "firebase": "^8.6.8"
