### ISSUE TITLE
Deployed app not working

### ISSUE THREAD

**Issue by Mayhem50** [firebase/polymerfire#46]
I have migrated my application from `firebase-element` to `polymerfire`. Everything works fine until I deploy the app. 
After, on local or on web many errors appear. 
On web, errors are :  `Uncaught NotSupportedError`, `Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a function`, etc
After deploying, on local, it seams that it's an iframe that points to `mywebsite.firebaseapp.com/__/auth` is corrupted. Errors are same.
The workarround I find is to have a project for auth and database and deploy on other project. It resolves only auth corruption.

After long search I thinl the problem comes from polymer build process

**Comment by napoo80** [comment]
I'm having the same problem, thanks for sharing your workarround.

I'm usign polymer-cli for building, @Mayhem50 are you?

**Comment by mgibas** [comment]
Very similar issues here.
In my case `mywebsite.firebaseapp.com/__/auth` iframe doubles or triples every request.

example:
https://project-3846386819515834955.firebaseapp.com/

**Comment by bryanwood** [comment]
Try this in your `firebase.json`

```
"rewrites": [
      {
        "source": "**!(/__/**)",
        "destination": "/index.html"
      }
    ]
```

**Comment by mbleigh** [comment]
@mgibas I'm not seeing any errors when I open your site -- did you work out the problem?

**Comment by bryanwood** [comment]
I'm also hitting this issue, the suggested rewrite is causing requests to /__/auth and similar to return the contents of index.html

**Comment by mbleigh** [comment]
Are you configuring your `auth-domain` on `firebase-app` correctly? If you're pointing it at a `firebaseapp.com` domain there shouldn't be an issue here...

**Comment by Quelu** [comment]
Yes same here and I've correctly configured my `auth-domain` both in the Firebase console and in my `firebase-app` but I still have the issue. 
The only way to have the auth working is with the workaround given by @Mayhem50 

I'm also using the polymer-cli for building my project, could this issue come from this ?
[Here is my project](https://memopet-test.firebaseapp.com) to let you try auth.

**Comment by mgibas** [comment]
@mbleigh yeah, I had to deploy a fix - sorry for that.
It seams to be a polymer-cli issue cause I switched to gulp (configuration from PSK) and all issues went away.

**Comment by mbleigh** [comment]
@cdata any ideas on what this might be?

**Comment by mshockwave** [comment]
I use Polymer CLI and encountered the same problem

**Comment by mshockwave** [comment]
I use @Mayhem50 's solution and it works. I delete every rewrite rules in `firebase.json` but the problem is still exist, so perhaps the polymer build tool add some additional rewriting / forwarding rules?
I would like to forward this thread to issues of polymer-cli repo.

**Comment by locomuco** [comment]
solution found in https://github.com/Polymer/polymer-cli/issues/290
