### ISSUE TITLE
'X-Frame-Options' set to 'DENY' ?

### ISSUE THREAD

**Issue by myuseringithub** [firebase/polymerfire#49]
Error while trying to migrate to SDK 3Refused to display.

'https://console.firebase.google.com/project/XXXXX/database/data .... ' in a frame because it set 'X-Frame-Options' to 'DENY'.

What does it mean ?

**Comment by myuseringithub** [comment]
I started having this problem when trying to migrate to Firebase SDK 3. Before migrating everything was working just fine. 
Hope for a solution soon.

**Comment by locomuco** [comment]
I see the same problem..

**Comment by myuseringithub** [comment]
@locomuco Have you found a solution yet ?

**Comment by locomuco** [comment]
@myuseringithub no unfortunately not, but doesn't bother me enough to start searching for the root cause

**Comment by toastermagic** [comment]
Same issue here.

This is the reply I get from firebase:
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "keyExpired",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}
```

All the keys I know about are absolutely fine.

**Comment by mbleigh** [comment]
When does this error occur? On page load? I haven't seen this one myself...

**Comment by locomuco** [comment]
Happens on page load, yes

**Comment by mbleigh** [comment]
Does anyone have a public URL that exhibits this behavior? I've not been able to reproduce this.

**Comment by locomuco** [comment]
https://project-4156531278292366083.firebaseapp.com/#/blog

**Comment by mbleigh** [comment]
@locomuco your `auth-domain` is incorrect:

    auth-domain="project-4156531278292366083.firebaseio.com"

should be `firebaseapp.com` instead.

Is that potentially the problem for everyone here?

**Comment by locomuco** [comment]
solves my problem

**Comment by myuseringithub** [comment]
Solved mine too.
