### ISSUE TITLE
Get twitter @username with firebase.UserInfo

### ISSUE THREAD

**Issue by bkawk** [firebase/polymerfire#51]
### Expected outcome

@bkawk

### Actual outcome

No data 

### Steps to reproduce

1. Login with twitter
2. Try to access the twitter @username / handle with firebase.UserInfo

**Comment by TStrauch** [comment]
Hey, I am facing the same problem. When authenticating with twitter via firebase the returned user object does not contain the twitter handle. How did you resolve this?
