### ISSUE TITLE
Support for "shallow" URI parameter

### ISSUE THREAD

**Issue by paultdf** [firebase/polymerfire#52]
Is there any intention to implement the "shallow" URI parameter here?

https://firebase.google.com/docs/database/rest/retrieve-data#shallow

Ideally this would be usable in both firebase-document and firebase-query (though I understand data filtering options don't work with it)

**Comment by mbleigh** [comment]
PolymerFire doesn't use the REST API, which is the only place that `shallow` is available. You can directly make REST calls using something like `iron-ajax`, but I don't intend to support it in PolymerFire as the bindings are meant to work with the JS SDK.

Also, relying on shallow is generally a non-performant and ill-advised thing to do in Firebase-land -- it tends to be a code smell. I'd recommend trying to structure your data such that you don't need shallow.
