### ISSUE TITLE
Possible typo in firebase-document in the method __onFirebaseValue.

### ISSUE THREAD

**Issue by kritollm** [firebase/polymerfire#56]
I just can't understand these lines of code, and the this.new is always undefined:

`if (!this.new) {
        this.async(function() {
          this.syncToMemory(function() {
            this._log('Updating data from Firebase value:', value);
            this.set('data', value);
          });
        });
      }`

Should it may be:

`if (!this.isNew) {
        this.async(function() {
          this.syncToMemory(function() {
            this._log('Updating data from Firebase value:', value);
            this.set('data', value);
          });
        });
      }`

**Comment by christophe-g** [comment]
Agree, this looks like a bug
