### ISSUE TITLE
Firebase-query Equal To Issue

### ISSUE THREAD

**Issue by merc37** [firebase/polymerfire#59]
### Description

Setting the `equal-to` attribute to a boolean type does not work as expected when its value is `false`. The attribute works as expected when boolean and `true`, or other types.

### Expected outcome
When a document in the Firebase database has a child in it set to `true`, and the firebase-query attribute `equal-to` is set to `false`, the query should not return that document.

### Actual outcome
It returns all documents, ignoring the equalTo. If the values were instead Strings or `equal-to` is set to `true`, it works as expected.

### Live Demo

[Link to demo](https://jsbin.com/qaloxozagu/1/edit?html,output)

### Steps to reproduce

1. The demo starts with equal-to being boolean `false`. The expected `false` results should be a single line of "Boolean value of false", instead all documents are listed.
2. After clicking test true, `equal-to` is set to boolean `true`, a single line of "Boolean value of true" is shown as expected.

[Link to database](https://equaltoissue.firebaseio.com/.json)

**Comment by mbleigh** [comment]
#98 should fix this.
