### ISSUE TITLE
Cannot create property '$key' on boolean 'true'

### ISSUE THREAD

**Issue by ExWei** [firebase/polymerfire#6]
### Description
When using `<firebase-query>` with data structure like
```
{
$id: true
}
```
it throws an error
`Cannot create property '$key' on boolean 'true'`
## Steps to reproduce
Create data like
```
{
    "notes-by-user": {
        "userId1": {
            "noteId1": true,
            "noteId2": true,
        }
    }
}
```
and `<firebase-query>` element like
```
<firebase-query
   path="/notes-by-user/userId1"
   data="{{notes}}">
</firebase-query>
```

**Comment by cdata** [comment]
Hi, thanks for reporting. Using `<firebase-query>` on locations where all of the children have primitive (`boolean`, `string`, `number`) values is not supported. Please consider nesting these values in objects.

**Comment by darktears** [comment]
But https://firebase.google.com/docs/database/web/structure-data#fanout actually give the above as an example.

**Comment by darktears** [comment]
@cdata this limitation pretty much kills doing fast lookup on the key. In the example I pasted there is no way one could do groups/[[an_id]]. Now one has to get the entire collection (groups) and iterate over it, it doesn't seem to scale TBH. Maybe you have a better suggestion.

**Comment by salah-saleh** [comment]
Hi @cdata, I also stumbled  upon this issue today. I think this limitation is a real concern and the issue shouldn't be closed without fixing, or what do you think?

**Comment by midesweb** [comment]
I think so. this is a serious limitation. Firebase team should open the issue again.

**Comment by midesweb** [comment]
As workaround you can use firebase-document instead of firebase-query.
And then use a new element to convert your object into an array, like this:

`<firebase-document
      app-name="{{firebaseApp}}"
      path="[[locAutoresD]]"
      data="{{autoresAsociadosDocument}}"
    ></firebase-document>
    <object-to-array
      object="[[autoresAsociadosDocument]]"
      array="{{autoresAsociados}}"
    ></object-to-array>`

The element "object-to-array" should be like this:

`<dom-module id="object-to-array">
  <script>
  (function() {
    'use strict';

    Polymer({
      is: 'object-to-array',

      properties: {
        object: {
          type: Object,
          observer: 'toArray'
        },
        array: {
          type: Array,
          notify: true
        }
      },
      toArray: function(o) {
        if(o){
          var newArray = [];
          for (var id in o){
            newArray.push(id);
          }
          this.array = newArray;
        }
      }

    });
  })();
  </script>
</dom-module>
`

**Comment by bvhme** [comment]
We've also structured our firebase this way according with the Firebase docs' explanation that you should work in the way @ExWei showed. I found out this didn't work when I noticed that `firebase-query` misses a `orderByValue` option. Our whole platform is built on this design pattern, so upgrading from `firebase-element` to `polymerfire` is very dificult for us.
