### ISSUE TITLE
signInWithEmailAndPassword throws error

### ISSUE THREAD

**Issue by milesje** [firebase/polymerfire#61]
### Description
Attempting to use signInWithEmailAndPassword throws and exception

### Expected outcome
method should be found and executed.

### Actual outcome
market-edge-app.html:51 Uncaught TypeError: this.$.auth.signInWithEmailAndPassword is not a function
signIn	@	market-edge-app.html:51
handler	@	polymer.html:518
fire	@	polymer.html:1277
signIn	@	me-login.html:70
handler	@	polymer.html:518
fire	@	polymer.html:1277
fire	@	polymer.html:854
forward	@	polymer.html:1149
click	@	polymer.html:1134
handleNative	@	polymer.html:744

Not sure if I  have something configured wrong or what but I started with a basic polymer app built using the polymer-cli, I then added polymerfire using bower I have setup the firebase-app with the correct setting from my firebase-console.
Below is a snippet of the code.

  ```
  <firebase-auth
        id="auth"
        app-name="market-edge"
        signed-in="{{signedIn}}"
        user="{{user}}">
    </firebase-auth>

  </template>

  <script>
    Polymer({

      is: 'market-edge-app',

      properties: {
      },
      signIn: function() {
        console.log(this.$.auth.user);
        this.$.auth.signInWithEmailAndPassword(this.user, this.password)
          .then(function(response) {
            console.log(response);
          })
          .catch(function(error) {
            console.log(error);
          });
      }
    });
  </script> 
```

**Comment by milesje** [comment]
I changed my code as follows and now the signIn function works. This should really work either way and I'm not sure why it works one way and not the other.

```
<firebase-auth
        id="auth"
        app-name="market-edge"
        signed-in="{{signedIn}}"
        user="{{user}}">
    </firebase-auth>

  </template>

  <script>
  (() => {
    'use strict'

    Polymer({

      is: 'market-edge-app',

      properties: {
      },
      signIn() {
        console.log(this.$.auth.user);
        this.$.auth.signInWithEmailAndPassword(this.user, this.password)
          .then(function(response) {
            console.log(response);
          })
          .catch(function(error) {
            console.log(error);
          });
      }
    });
  })();
  </script>
```

**Comment by mbleigh** [comment]
Since signInWithEmailAndPassword is [definitely defined](https://github.com/firebase/polymerfire/blob/master/firebase-auth.html#L174) on the auth element, I'm guessing this may have been some kind of initialization or timing error in your app code somewhere...I'm unable to repro and am closing barring a concrete repro. Thanks!
