### ISSUE TITLE
Value reading issue of firebase-document wrapped in dom-if in non-Chrome browsers

### ISSUE THREAD

**Issue by mshockwave** [firebase/polymerfire#65]
### Description
One of the common scenarios is that I need to read an user specific value with database layout:
```
/users/$user_id/foo
```
But since user id is required, we need to wait until firebase `User` object(`fbUser` in short) is available. So I would wrapped `firebase-document` in a `dom-if`:
```
<template is="dom-if" if="[[fbUser]]" restamp="true">
  <firebase-document
    path="/users/[[fbUser.uid]]/foo"
    data="{{fooData}}"></firebase-document>
</template>
```
If I didn't wrap it in `dom-if`(with `restamp` be true), `firebase-document` seem to be unable to detect the change of `path` and failed to load value(even in Chrome).

Nevertheless, in non-Chrome browsers, although `dom-if` worked as expected and `firebase-document` is loaded after `fbUser` is available, I can't get any value from `fooData` not until I changed value of `/users/$user_id/foo` from the Firebase web console.

At first, I thought `firebase-document` have problem updating value at the first time with `dom-if`. But after I attached an observer on `fooData` to print its value, I got strange output below:(Value of `/users/$user_id/foo` is string "bar")
```
fooData: {}
fooData: "bar"
fooData: "bar"
fooData: {}
```

The only solution I came out is using dynamic evaluated `path` property of firebase-document:
```
<firebase-document
  id="fbFoo"
  data="{{fooData}}"></firebase-document>
...

observers:[
  '__onFbUserChanged(fbUser)'
],

__onFbUserChanged: function(fbUser){
  if(fbUser){
    this.$.fbFoo.path = '/users/' + fbUser.uid + '/foo';
  }
}
```

### Expected outcome

`firebase-document` in `dom-if` behave the same in all browsers

### Actual outcome

Data won't get any value when `firebase-document` in `dom-if` got attached

### Steps to reproduce
(Described above)

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [NOT TESTED] Edge
- [NOT TESTED] IE 11
- [NOT TESTED] IE 10

**Comment by mbleigh** [comment]
Can you test this on 0.9.5? It may have been addressed. You shouldn't need the dom-if
