### ISSUE TITLE
Feature R: Fire "snapshot"-event with response from firebase-document

### ISSUE THREAD

**Issue by tograd** [firebase/polymerfire#66]
If I want to initiate values on a document when it's accessed the first time all I can do is listen for changes to the `data` handle. But when you have set the path it'll trigger an empty obj which you don't really know if it's an empty document or just initiated zeroValue `data.` Right?

To solve this all I've done is add a line `this.fire("snapshot", value);` in firebase-document.html:194 and now I know for sure when first response occurs. **_edit: i've removed this event and instead made a separate `getStoredValue` request to see if the data exists, but my example below still stands I think._** 

Alternatively maybe set a 'status' variable so you are aware if it's in the pending state in between request and first response. Helps if you want to for example disable input fields while waiting for response, or fade in when response comes. 

Also maybe I'm going about this all wrong :p

**Comment by willydouhard** [comment]
I am having the same "issue". This is not a huge deal but I would expect to get the final value of the request instead of an empty object and THEN the value. This force me to check on the type of the response to avoid reacting to an intermediate state of my value. Or maybe like OP said I miss something.

**Comment by tjmonsi** [comment]
This might be connected to #33 
Let's close this for now until there's new activity about this.
