### ISSUE TITLE
Improve equalTo documentation

### ISSUE THREAD

**Issue by phidias51** [firebase/polymerfire#75]
Please update the equalTo property documentation in the firebase-query element to include an example for how it should work.

Is it supposed to be:
```
<firebase-query equal-to="{childNodeName: childNodeValue}"

or

<firebase-query equal-to="[[{'childNodeName': 'childNodeValue'}]]"

```

How are multiple parameters handled?  Are they OR'd together or AND'd?  Do you simply put in a boolean expression?

**Comment by tjmonsi** [comment]
Supposed to be this
```
<firebase-query equal-to="{{object}}"></firebase-query>
<script>
Polymer({
   ready() {
        this.object = { childNodeName: 'childNodeValue' };
   }
})
```

The problem with this is that in the [Firebase docs](https://firebase.google.com/docs/reference/js/firebase.database.Query#equalTo), the equalTo method takes in a string (value), and another string (key)... so it should be equalTo(value, key) and not equalTo(object)

I might take a look into this when I wake up later though and see if it works

**Comment by mbleigh** [comment]
`equalTo` is only applicable to leaf nodes, and cannot be used to match an object. What you would want is:

```html
<firebase-query order-by-child="childNodeName" equal-to="childNodeValue"></firebase-query>
```

**Comment by syu93** [comment]
Hi, 

Thx this does work for me.

You should update the documentation to refer to this particular issue, or can I make a pull request to update the doc ?

**Comment by Mvxt1** [comment]
Awesome. made my day!

**Comment by JGSolutions** [comment]
Is there a way to do go through nested objects?

**Comment by ThilinaTCH** [comment]
@JGSolutions I'm having the same issue, seems like not supporting nested objects. Meant ordered by deeply nested children. Firebase has that feature, refer 'Filtering by a specified child key' section in, https://firebase.google.com/docs/database/rest/retrieve-data.
But tried to query by ordering by deep nested child with equal-to using @mbleigh solution, but didn't worked.
@mbleigh Any idea on this issue?
