### ISSUE TITLE
Add support for LinkedIn in auth element

### ISSUE THREAD

**Issue by phidias51** [firebase/polymerfire#76]
Add support for logging in using LinkedIn.

**Comment by tjmonsi** [comment]
@phidias51 I was looking back at the Firebase docs and LinkedIn is not yet supported. The only ones that are supported are the following:
[Email/Password](https://firebase.google.com/docs/auth/web/password-auth)
[Gmail](https://firebase.google.com/docs/auth/web/google-signin)
[Facebook](https://firebase.google.com/docs/auth/web/facebook-login)
[Twitter](https://firebase.google.com/docs/auth/web/twitter-login)
[Github](https://firebase.google.com/docs/auth/web/github-auth)
[Custom](https://firebase.google.com/docs/auth/web/custom-auth)
and [Anonymous](https://firebase.google.com/docs/auth/web/anonymous-auth)

What I can suggest is to use a Custom authorization. Create a *service account key* on your Google Cloud Console as stated here (https://firebase.google.com/docs/auth/web/custom-auth). 

Then follow the steps here to authenticate your user (https://firebase.google.com/docs/auth/server/#create_a_custom_token)

The idea would probably be like this:
1. User clicks on your login button
2. A pop-up or redirection will send the user to a separate login page where they can send in their LinkedIn credentials
    - login page has its own separate server that has the Google Cloud service key, linkedIn credential system (maybe a linkedIn passport for NodeJS or something else)
3. once authenticated by LinkedIn, the server would create a custom token to be sent back to your original app
4. once sent back, the token is consumed using the `signInWithCustomToken()` method of the `firebase-auth` component

It's still a lot of work though :disappointed:

**Comment by mbleigh** [comment]
This is not relevant to PolymerFire, as we support everything supported by Firebase Auth. Feel free to [file a feature request](https://firebase.google.com/support/contact/bugs-features/).
