### ISSUE TITLE
Add documentation for auth user object

### ISSUE THREAD

**Issue by phidias51** [firebase/polymerfire#77]
Add documentation for the user object in the auth element.  What fields are available?  If you use different auth mechanisms, do the fields differ?

**Comment by esd100** [comment]
Right.  I can't figure out how to add the different ways of authentication, in particular for anonymous and for email:password cases.

**Comment by mbleigh** [comment]
The docs already seem to point here: https://firebase.google.com/docs/reference/js/firebase.User

Which is the comprehensive reference.
