### ISSUE TITLE
Suggestion: change name to "Polyfire" - shorter and sweeter, imho :-)

### ISSUE THREAD

**Issue by rchrdnsh** [firebase/polymerfire#78]
Please see subject for the point of the suggestion. The term "polymerfire" is just too long and awkward, not euphonic at all to me. I like "Polyfire" myself :-)

**Comment by mbleigh** [comment]
I appreciate the suggestion, but I'm going to err on the side of consistency -- Firebase official bindings always use the full framework name (e.g. AngularFire, ReactFire, EmberFire) and I'd like to keep it consistent. 😁
