### ISSUE TITLE
The state of signing in

### ISSUE THREAD

**Issue by dsnowdon** [firebase/polymerfire#83]
### Polymer fire method
When connecting to auth via polymer fire I have two variables ( at least that I know of ), from which i  should be able to determine the state of authentication. signedIn and user.

When a user is signed in and the website loads signedIn changes three times null, false then true. and user changes twice, null then [user object]

when a user isn't signed in:
signedIn goes, null then false
and user:
null

Both times, whether the user will be signed in or not, the signed in variable at some point is false.
Using polymer fire I am not able to wait until the state of the application has been determined. See below for a better method.

Why does the signedIn variable return false even when a user is about to be signed in?

### Standard Method
When a page loads, using the standard firebase SDK I normally used code like
```

properties: {
   user: {
      type: Object,
      value: null,
      observer: '_userChanged'
}
...
ready: function() {
firebase.onAuthStateChanged(function(user) {
if(user) that.user = user;
else that.user = false;
}); }

```

From the _user_ variable i can determine If the application has been loaded.

```

_userChanged: function(user)
{
if(this.user === null) 
{
    // the app has not yet been loaded
    // wait for the user to be determined before
    // i decided if or what page to open.  
}
else if(this.user === false {
   // the user isn't loggedin, 
   // load the home page
}
else if(user)
{
    // load the dashboard
} 
}

```

**Comment by thinkallabout** [comment]
I would like to know this also. Turns out when using `<firebase-auth>` the sign in state changes, however with the library on it's own it's fine. I got around this by waiting for auth before loading my application shell (using the firebase library on it's own), however this obviously has significant latency issues and is a temporary fix during development, at best.

**Comment by Quelu** [comment]
Check this PR #24 that's the solution but we're waiting to get this merge in.
