### ISSUE TITLE
Service worker doesn't allow Firebase Auth redirecting

### ISSUE THREAD

**Issue by motss** [firebase/polymerfire#86]
### Description
With Service Worker enabled, Firebase Auth redirection does not work and it seems like sw intercept the network request while hitting the URL `https://example.firebaseapp.com/__/auth/handler?apiKey=<api_key>...` (too long) for authentication for both redirect and popup and treats the URL like one of the sub pages of my application.

However, without Service Worker, the authentication works fine and it is able to redirect to `https://example.firebaseapp.com/__/auth/handler?apiKey=<api_key>...` then back to the URL of the application.

### Expected outcome

Firebase Auth works with Service Worker enabled.

### Actual outcome

Service Worker seems like intercepting the network request while hitting URL `https://example.firebaseapp.com/__/auth/handler?apiKey=<api_key>...`.

### Steps to reproduce
1. Create a demo with sub-pages routing with `app-route` and use `firebase-auth` for authentication.
2. Build the demo with `sw` enabled.
3. Login and see demo stops redirection while hitting the URL `https://example.firebaseapp.com/__/auth/handler?apiKey=<api_key>...`.
4. If Chrome Canary is used, tick `Bypass for network` on the `Service Workers` section under `Application` tab in Dev Tools. Try log in again and see redirection works fine.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by midesweb** [comment]
It seems to be the same problem of this issue: [https://github.com/Polymer/polymer-cli/issues/290](https://github.com/Polymer/polymer-cli/issues/290)
The link provided has the solution and explanation to configure the service worker properly

**Comment by motss** [comment]
@midesweb Thanks for the information.
