### ISSUE TITLE
New Api Method Request

### ISSUE THREAD

**Issue by JGSolutions** [firebase/polymerfire#89]
Not really an issue but just wondering if there will be any support for converting an anonymous account to a permanent account using the firebase.auth.EmailPasswordAuthProvider.

**Comment by mbleigh** [comment]
You should be able to do this already:

```html
<firebase-auth user="{{user}}"></firebase-auth>
<script>
  this.$.user.link(new firebase.auth.EmailAuthProvider().credential(username, password));
</script>
```

**Comment by JGSolutions** [comment]
Hi @mbleigh 

I tried the above example and .link is not a function. I checked the polymerfire code base including the firebase-auth and not link() function exists.

Am i missing something?

Thanks in advance.
