### ISSUE TITLE
Add ability to link accounts using the firebase-auth element.

### ISSUE THREAD

**Issue by MarcMouallem** [firebase/polymerfire#91]
Add the account linking feature available in the JavaScript SDK documented [here](https://firebase.google.com/docs/auth/web/account-linking).

**Comment by dsnowdon** [comment]
Why not just

```
_linkGoogleAccount: function()
			{
				var user = this.user;
				var provider = new firebase.auth.GoogleAuthProvider();
				var that = this;

				user.linkWithPopup(provider).then(function(result) {
					console.log('sucess');
					console.log(result);
					that._updateUserEmail(result.user.email);
				}, function(error) {
					console.log(error);
				});	
			},```

Where _this.user_ equals a Anonymous User

**Comment by MarcMouallem** [comment]
Did not think that Polymerfire exposed the Firebase global var.

**Comment by JGSolutions** [comment]
@MarcMouallem does this actually work for you? This global firebase needs to have an existing instance and i get this error

`
firebase.js:26 Uncaught Error: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp().
`

**Comment by MarcMouallem** [comment]
```
<firebase-app 
  api-key="..."
  app="{{firebaseApp}}"`
  auth-domain="example.firebaseapp.com"
  database-url="https://example.firebaseio.com"
  name="myApp">
</firebase-app>
```

`firebaseApp` is a native [Firebase object](https://firebase.google.com/docs/reference/js/firebase.app.App). Pass `firebaseApp` to your Polymer elements that need it via [declared properties](https://www.polymer-project.org/1.0/docs/devguide/properties).

**Comment by dshukertjr** [comment]
I am trying to link an anonymous account to an email and password account, but I cannot get it to work. 

In my element, I have

```
    <firebase-auth 
      app="{{firebase}}"
      id="auth" 
      user="{{user}}" 
      on-error="handleError">
    </firebase-auth>
```

and I have a method like this: 

```

      mergeAccount(){
        const email = this.$.email.value;
        const password = this.$.password.value;
        const firebase = this.firebase;
        const auth = firebase.auth();

          var credential = auth.EmailAuthProvider.credential(email, password);
          auth.currentUser.link(credential).then(function(user) {
          }, function(error) {
            console.log("Error upgrading anonymous account", error);
          });
      }

```

Now this gives me the following error: 
Uncaught TypeError: Cannot read property 'credential' of undefined

What am I doing wrong? I guess what the unclear part in the documentation here
https://firebase.google.com/docs/auth/web/anonymous-auth
is what "firebase" variable and what "auth" variable actually is.

**Comment by dshukertjr** [comment]
No one?

**Comment by tjmonsi** [comment]
Did you try having a firebase-app? In my projects, I can access the firebase variable easily

**Comment by dshukertjr** [comment]
Okay, I was able to access the firebase variable with "window.firebase", but now I cannot access the auth variable in this example: 

https://firebase.google.com/docs/auth/web/anonymous-auth

```
auth.currentUser.link(credential).then(function(user) {
  console.log("Anonymous account successfully upgraded", user);
}, function(error) {
  console.log("Error upgrading anonymous account", error);
});
```

this variable "auth" seems to come from no where without any explanation, and it seems like it's not a global variable. Is it "firebase.auth", or "firebase.auth()", or something else? I have tried the first two, but got an error

**Comment by dshukertjr** [comment]
I have also done this, but I got the following error
```
auth.currentUser.link(credential).then(function(user) {
  console.log("Anonymous account successfully upgraded", user);
}, function(error) {
  console.log("Error upgrading anonymous account", error);
});
```
```
Uncaught TypeError: this.user.link is not a function
    at HTMLElement.signup (my-user.html:169)
```

where I have 
```
    <firebase-auth 
      id="auth"
      user="{{user}}"
      on-error="handleError">
    </firebase-auth>
```

**Comment by tjmonsi** [comment]
Try `window.firebase.auth`

**Comment by dshukertjr** [comment]
So I have this
```
           const firebase = window.firebase
            var credential = firebase.auth.EmailAuthProvider.credential(email, password)

            firebase.auth.currentUser.link(credential).then(function(user) {
              console.log('successfully upgraded')
            }, function(error) {
              console.log("Error upgrading anonymous account", error)
            })
```
and this as the output
```
my-user.html:169 Uncaught TypeError: Cannot read property 'link' of undefined
```

So I guess it's not "window.firebase.auth" ?
I also tryed "window.firebase.auth()", but no luck there either

**Comment by tjmonsi** [comment]
auth is existing. It is the currentUser that doesn't exist. It means there is no user logged in

**Comment by dshukertjr** [comment]
I actually do have user logged in as
```
console.log(this.user.uid)
```
outputs an user id something like
```
s3sCdZvkHdbj916Q1HkE7fnGd8J5
```

**Comment by dshukertjr** [comment]
Also, when I did this
```
this.$.auth.auth.currentUser.link(credential)
````
I got this
```
this.$.auth.auth.currentUser.link is not a function
```
Which seems closer to a solution, but not quite

**Comment by dshukertjr** [comment]
The problem here probably is that my "this.$.auth.auth" or "firebase.auth().currentUser" does not have a "link" method for some reason.

**Comment by dshukertjr** [comment]
I inspected the "this.$.auth.auth.currentUser" in the console log and found these methods, but not link

```
linkAndRetrieveDataWithCredential:function a()
linkWithCredential:function a()
linkWithPhoneNumber:function a()
linkWithPopup:function a()
linkWithRedirect:function a()
```
Has the link method been deprecated? If so, someone should update the documentation....

**Comment by dshukertjr** [comment]
I used 
```
this.$.auth.auth.currentUser.linkWithCredential(credential)
```
and I was able to link my anonymous user to email and password. 

Can someone update the documentation [here](https://firebase.google.com/docs/auth/web/anonymous-auth) from just using "link" to using "linkWithCredential" ?

**Comment by tjmonsi** [comment]
I think you can put a word at the firebase website about that.

**Comment by JGSolutions** [comment]
So from my understand from all of this...the link method does not exist? We should use linkWithCredential?

**Comment by JGSolutions** [comment]
Also when I use this linkWithCredential it says the account already exists. Yes it does but this is why I want to link the account

**Comment by BinaryNate** [comment]
+1 for updating the documentation. That would have saved me some time and confusion.
