### ISSUE TITLE
Firebase-app Errors & Warnings

### ISSUE THREAD

**Issue by JGSolutions** [firebase/polymerfire#97]
### Description
First load everything is fine but refreshing web app firebase-app spitting out warnings and errors and CPU usage goes over 100%. This is happening only in chrome.

### Expected outcome
No errors no happen

### Actual outcome
CPU usage goes over 100%  & errors in console log. Url of demo is below

### Live Demo
https://online-resto.firebaseapp.com/

### Steps to reproduce

1. Load app first time is fine.
2. refresh and check the console log.

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by mbleigh** [comment]
Have you tried clearing your service worker cache completely? I'm unable to
repro by visiting your referenced site.

**Comment by JGSolutions** [comment]
No I didn't clear my service worker cache. But I can't reproduce it either anymore. Probably something was cached because firefox and safari were fine.

But thanks for letting me know about the service worker caching tip. If this issue ever arises again I will know what to do.

This issue can be closed and thanks again.

**Comment by JGSolutions** [comment]
I am getting the errors again and I added a screenshot. 

I also use this to clear the service workers: chrome://serviceworker-internals/. 

Not sure if this tip works and makes sense to me. If my users have service worker cached they will always get these errors? 

![errors](https://cloud.githubusercontent.com/assets/197318/17757122/968621d6-64b2-11e6-8688-bfdc2c4570f8.jpg)
